"""
Shared Workspace Routes - public endpoints for viewing workspace files via tokens.

These endpoints don't require regular user authentication. Instead, they use
short-lived workspace view tokens (JWTs) generated by the /files command
for A2A clients.
"""
import uuid
import logging

from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import StreamingResponse

from app.models import AgentEnvironment
from app.services.agent_workspace_token_service import AgentWorkspaceTokenService
from app.services.environment_service import EnvironmentService
from app.core.db import create_session

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/shared/workspace", tags=["shared-workspace"])


@router.get("/{env_id}/view/{path:path}")
async def view_shared_workspace_file(
    env_id: uuid.UUID,
    path: str,
    token: str = Query(..., description="Workspace view token"),
):
    """
    View a workspace file using a short-lived token (no user auth required).

    Used by A2A clients to open file links from /files command responses
    in a browser.

    Args:
        env_id: Environment ID
        path: Relative path from workspace root
        token: Workspace view JWT token
    """
    # Validate token
    payload = AgentWorkspaceTokenService.verify_workspace_view_token(token)
    if not payload:
        raise HTTPException(status_code=401, detail="Invalid or expired token")

    # Verify env_id matches token
    if payload.get("env_id") != str(env_id):
        raise HTTPException(status_code=403, detail="Token does not match environment")

    # Get environment and check it's running
    with create_session() as db:
        environment = db.get(AgentEnvironment, env_id)
        if not environment:
            raise HTTPException(status_code=404, detail="Environment not found")
        if environment.status != "running":
            raise HTTPException(
                status_code=400,
                detail=f"Environment is not running (status: {environment.status})"
            )

    # Stream file content via adapter
    try:
        lifecycle_manager = EnvironmentService.get_lifecycle_manager()
        adapter = lifecycle_manager.get_adapter(environment)

        async def stream_file():
            async for chunk in adapter.download_workspace_item(path):
                yield chunk

        return StreamingResponse(
            stream_file(),
            media_type="text/plain; charset=utf-8",
            headers={"X-Accel-Buffering": "no"},
        )

    except FileNotFoundError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        logger.error(f"Failed to view shared workspace file: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Failed to view file: {str(e)}")
