# Re-export all models for backward compatibility
from sqlmodel import SQLModel
from .credentials.link_models import AgentCredentialLink
from .users.user import (
    User,
    UserCreate,
    UserRegister,
    UserUpdate,
    UserUpdateMe,
    UserPublic,
    UsersPublic,
    UserSearchResult,
    UsersSearchPublic,
    UserRole,
    UserRolePublic,
    UserRoleUpdate,
    UpdatePassword,
    Message,
    NewPassword,
    Token,
    TokenPayload,
    SetPassword,
    OAuthConfig,
)
from .users.user_passkey import (
    UserPasskey,
    UserPasskeyPublic,
    UserPasskeysPublic,
    UserPasskeyUpdate,
)
from .users.user_totp_secret import (
    UserTotpSecret,
    TotpEnrollResponse,
    TotpFinishRequest,
)
from .users.user_recovery_code import (
    UserRecoveryCode,
    RecoveryCodeStatus,
    RecoveryCodesPlaintext,
)
from .users.user_trusted_device import (
    UserTrustedDevice,
    TrustedDevicePublic,
)
from .users.user_mfa_challenge import (
    UserMfaChallenge,
    MfaFirstFactor,
    MfaChallenge,
    MfaVerifyRequest,
    LoginToken,
    LoginResponse,
    MfaStatus,
    StepUpProof,
    PasskeyAuthOptionsRequest,
    PasskeyAuthOptionsResponse,
)
from .agents.agent import (
    Agent,
    AgentCreate,
    AgentUpdate,
    AgentPublic,
    AgentsPublic,
    AgentWithCredentials,
    AgentCredentialLinkRequest,
    AgentCreateFlowRequest,
    AgentCreateFlowResponse,
    AgentSdkConfig,
    AllowedToolsUpdate,
    PendingToolsResponse,
    GenerateRouterTriggerPromptResponse,
    RouterTriggerPromptUpdate,
    UpdateMode,
)
from .credentials.credential import (
    Credential,
    CredentialCreate,
    CredentialUpdate,
    CredentialPublic,
    CredentialsPublic,
    CredentialBundleUsage,
    CredentialBundleUsages,
    CredentialAffectedAgent,
    CredentialDeletionImpact,
    CredentialType,
    EmailImapData,
    OdooData,
    GmailOAuthData,
    ApiTokenData,
    SSHKeyCredentialData,
    CredentialWithData,
)
from .credentials.ai_credential import (
    AICredential,
    AICredentialCreate,
    AICredentialUpdate,
    AICredentialPublic,
    AICredentialsPublic,
    AICredentialType,
    AICredentialData,
    AICredentialBundleUsage,
    AICredentialDeletionImpact,
)
from .credentials.ai_credential_share import (
    AICredentialShare,
    AICredentialShareBase,
    AICredentialSharePublic,
    AICredentialShareCreate,
    AICredentialSharesPublic,
    SharedAICredentialPublic,
    SharedAICredentialsPublic,
)
from .credentials.credential_share import (
    CredentialShare,
    CredentialShareBase,
    CredentialSharePublic,
    CredentialShareCreate,
    CredentialSharesPublic,
    SharedCredentialPublic,
    SharedCredentialsPublic,
)
from .bundles.agent_bundle import (
    AgentBundle,
    AgentBundleBase,
    AgentBundlePublic,
    AgentBundlesPublic,
    AgentBundleUpdate,
    BundleVisibility,
    BundleInstallMode,
)
from .bundles.agent_bundle_revision import (
    AgentBundleRevision,
    AgentBundleRevisionPublic,
    AgentBundleRevisionsPublic,
    PublishRequest,
)
from .bundles.bundle_access_grant import (
    BundleAccessGrant,
    BundleAccessGrantPublic,
    BundleAccessGrantsPublic,
    BundleAccessGrantCreate,
)
from .bundles.catalog import (
    CatalogEntryPublic,
    CatalogPublic,
    AICredentialSelections,
    InstallRequest,
    InstallCredentialSelection,
    AdminInstallRequest,
    SetUpdateModeRequest,
    EditBundleIdRequest,
    CheckUpdatesResponse,
    CatalogInstallContext,
    InstallContextSpec,
    InstallContextAIPublisherSummaries,
    InstallContextPublisherSummary,
    CredentialSpecDrift,
    BundleCredentialDrift,
)
from .environments.environment import (
    AgentEnvironment,
    AgentEnvironmentCreate,
    AgentEnvironmentUpdate,
    AgentEnvironmentReconfigure,
    AgentEnvironmentPublic,
    AgentEnvironmentsPublic,
    AdminAgentEnvironmentPublic,
    AdminAgentEnvironmentsPublic,
    AdminTemplateInfoPublic,
    AdminBulkSkipped,
    AdminBulkRebuildRequest,
    AdminBulkRebuildResponse,
)
from .agents.agent_status import (
    AgentStatusPublic,
    AgentStatusListPublic,
)
from .sessions.session import (
    Session,
    SessionCreate,
    SessionUpdate,
    SessionPublic,
    SessionPublicExtended,
    SessionsPublic,
    SessionsPublicExtended,
    SessionMessage,
    MessageCreate,
    MessagePublic,
    MessagesPublic,
    SessionCommandPublic,
    SessionCommandsPublic,
)
from .sessions.session_sender import (
    ChannelAccessPolicy,
    IngestionResult,
    SessionSender,
    SessionSenderKind,
    get_session_sender,
)
from .sessions.activity import (
    Activity,
    ActivityCreate,
    ActivityUpdate,
    ActivityPublic,
    ActivityPublicExtended,
    ActivitiesPublic,
    ActivitiesPublicExtended,
    ActivityStats,
)
from .events.event import (
    EventType,
    EventBase,
    EventPublic,
    EventBroadcast,
    ConnectionInfo,
)
from .agents.agent_schedule import (
    AgentSchedule,
    ScheduleRequest,
    ScheduleResponse,
    CreateScheduleRequest,
    UpdateScheduleRequest,
    AgentSchedulePublic,
    AgentSchedulesPublic,
)
from .agents.agent_schedule_log import (
    AgentScheduleLog,
    AgentScheduleLogPublic,
    AgentScheduleLogsPublic,
)
from .agents.agent_webhook import (
    AgentWebhook,
    AgentWebhookType,
    AgentWebhookCreateSession,
    AgentWebhookCreateScript,
    AgentWebhookUpdate,
    AgentWebhookPublic,
    AgentWebhookPublicWithToken,
    AgentWebhooksPublic,
)
from .agents.agent_webhook_log import (
    AgentWebhookLog,
    AgentWebhookLogPublic,
    AgentWebhookLogsPublic,
)
from .agents.agent_handover import (
    AgentHandoverConfig,
    HandoverConfigCreate,
    HandoverConfigUpdate,
    HandoverConfigPublic,
    HandoverConfigsPublic,
    GenerateHandoverPromptRequest,
    GenerateHandoverPromptResponse,
    CreateAgentTaskRequest,
    CreateAgentTaskResponse,
    ExecuteHandoverRequest,  # Deprecated, use CreateAgentTaskRequest
    ExecuteHandoverResponse,  # Deprecated, use CreateAgentTaskResponse
    UpdateSessionStateRequest,
    UpdateSessionStateResponse,
    RespondToTaskRequest,
)
from .users.user_workspace import (
    UserWorkspace,
    UserWorkspaceCreate,
    UserWorkspaceUpdate,
    UserWorkspacePublic,
    UserWorkspacesPublic,
)
from .users.ssh_key import (
    UserSSHKey,
    SSHKeyGenerate,
    SSHKeyImport,
    SSHKeyPublic,
    SSHKeysPublic,
    SSHKeyUpdate,
)
from .knowledge.knowledge import (
    AIKnowledgeGitRepo,
    AIKnowledgeGitRepoCreate,
    AIKnowledgeGitRepoUpdate,
    AIKnowledgeGitRepoPublic,
    AIKnowledgeGitRepoWorkspace,
    UserEnabledDiscoverableSource,
    DiscoverableSourcePublic,
    KnowledgeArticle,
    KnowledgeArticlePublic,
    KnowledgeArticleDetail,
    KnowledgeArticleChunk,
    KnowledgeArticleChunkPublic,
    SourceStatus,
    WorkspaceAccessType,
    CheckAccessResponse,
    RefreshKnowledgeResponse,
    ArticleListItem,
    ArticleContent,
)
from .plugins.llm_plugin import (
    LLMPluginMarketplace,
    LLMPluginMarketplaceCreate,
    LLMPluginMarketplaceUpdate,
    LLMPluginMarketplacePublic,
    LLMPluginMarketplacesPublic,
    LLMPluginMarketplacePlugin,
    LLMPluginMarketplacePluginPublic,
    LLMPluginMarketplacePluginsPublic,
    AgentPluginLink,
    AgentPluginLinkCreate,
    AgentPluginLinkUpdate,
    AgentPluginLinkPublic,
    AgentPluginLinkWithPlugin,
    AgentPluginLinkWithUpdateInfo,
    AgentPluginLinksPublic,
    MarketplaceStatus,
    PluginSourceType,
)
from .a2a.agent_access_token import (
    AgentAccessToken,
    AgentAccessTokenCreate,
    AgentAccessTokenUpdate,
    AgentAccessTokenPublic,
    AgentAccessTokenCreated,
    AgentAccessTokensPublic,
    AccessTokenMode,
    AccessTokenScope,
    A2ATokenPayload,
)
from .agent_api.agent_api_token import (
    AgentApiToken,
    AgentApiTokenBase,
    AgentApiTokenCreate,
    AgentApiTokenPublic,
    AgentApiTokenCreated,
    AgentApiConnectedAgent,
    AgentApiConnectionInfo,
    AgentApiProducerConnection,
    AgentApiProducerConnections,
    ConnectAgentApiRequest,
    ConnectAgentApiResponse,
)
from .sharing.agent_guest_share import (
    AgentGuestShare,
    AgentGuestShareBase,
    AgentGuestShareCreate,
    AgentGuestShareUpdate,
    AgentGuestSharePublic,
    AgentGuestShareCreated,
    AgentGuestSharesPublic,
    GuestShareGrant,
    GuestShareTokenPayload,
)
from .tasks.input_task import (
    InputTask,
    InputTaskCreate,
    InputTaskUpdate,
    InputTaskPublic,
    InputTaskPublicExtended,
    InputTaskDetailPublic,
    InputTasksPublic,
    InputTasksPublicExtended,
    InputTaskStatus,
    RefinementHistoryItem,
    RefineTaskRequest,
    RefineTaskResponse,
    ExecuteTaskRequest,
    ExecuteTaskResponse,
    SendAnswerRequest,
    SendAnswerResponse,
    AgentTaskStatusUpdate,
    AgentSubtaskCreate,
    AgentTaskCreate,
    AgentTaskOperationResponse,
)
from .tasks.task_comment import (
    TaskComment,
    TaskCommentBase,
    TaskCommentCreate,
    AgentTaskCommentCreate,
    TaskCommentPublic,
    TaskCommentsPublic,
    AgentCommentResponse,
)
from .tasks.task_attachment import (
    TaskAttachment,
    TaskAttachmentBase,
    TaskAttachmentPublic,
    TaskAttachmentsPublic,
)
from .tasks.task_status_history import (
    TaskStatusHistory,
    TaskStatusHistoryPublic,
    TaskStatusHistoriesPublic,
)
from .tasks.task_trigger import (
    TaskTrigger,
    TriggerType,
    TaskTriggerCreateSchedule,
    TaskTriggerCreateExactDate,
    TaskTriggerCreateWebhook,
    TaskTriggerUpdate,
    TaskTriggerPublic,
    TaskTriggerPublicWithToken,
    TaskTriggersPublic,
)
from .email.agent_email_integration import (
    AgentEmailIntegration,
    AgentEmailIntegrationCreate,
    AgentEmailIntegrationUpdate,
    AgentEmailIntegrationPublic,
    EmailAccessMode,
    EmailCloneShareMode,
    EmailProcessAs,
    ProcessEmailsResult,
)
from .email.mail_server_config import (
    MailServerConfig,
    MailServerConfigCreate,
    MailServerConfigUpdate,
    MailServerConfigPublic,
    MailServerConfigsPublic,
    MailServerType,
    EncryptionType,
)
from .email.email_message import (
    EmailMessage,
    EmailMessagePublic,
)
from .email.outgoing_email_queue import (
    OutgoingEmailQueue,
    OutgoingEmailQueuePublic,
    OutgoingEmailStatus,
)
from .mcp.mcp_connector import (
    MCPConnector,
    MCPConnectorCreate,
    MCPConnectorUpdate,
    MCPConnectorPublic,
    MCPConnectorsPublic,
)
from .mcp.mcp_oauth_client import (
    MCPOAuthClient,
    MCPOAuthClientPublic,
)
from .mcp.mcp_auth_code import (
    MCPAuthCode,
    MCPAuthRequest,
)
from .mcp.mcp_token import (
    MCPToken,
)
from .mcp.mcp_session_meta import (
    MCPSessionMeta,
    MCPSessionMetaPublic,
)
from .mcp.mcp_transport_session import (
    MCPTransportSession,
)
from .webapp.agent_webapp_share import (
    AgentWebappShare,
    AgentWebappShareBase,
    AgentWebappShareCreate,
    AgentWebappShareUpdate,
    AgentWebappSharePublic,
    AgentWebappShareCreated,
    AgentWebappSharesPublic,
    WebappShareTokenPayload,
)
from .webapp.agent_webapp_interface_config import (
    AgentWebappInterfaceConfig,
    AgentWebappInterfaceConfigBase,
    AgentWebappInterfaceConfigCreate,
    AgentWebappInterfaceConfigUpdate,
    AgentWebappInterfaceConfigPublic,
)
from .events.security_event import (
    SecurityEvent,
    SecurityEventCreate,
    SecurityEventPublic,
    SecurityEventsPublic,
    CREDENTIAL_READ_ATTEMPT,
    CREDENTIAL_BASH_ACCESS,
    OUTPUT_REDACTED,
    CREDENTIAL_WRITE_ATTEMPT,
    MFA_ENROLLED,
    MFA_DISABLED,
    MFA_CHALLENGE_ISSUED,
    MFA_CHALLENGE_SUCCESS,
    MFA_CHALLENGE_FAILED,
    MFA_RECOVERY_CODE_USED,
    MFA_RATE_LIMITED,
    MFA_SIGN_COUNT_REGRESSION,
    MFA_PASSKEY_INVALID_ORIGIN,
    MFA_RECOVERY_CODES_REGENERATED,
)
from .users.user_dashboard import (
    UserDashboard,
    UserDashboardCreate,
    UserDashboardUpdate,
    UserDashboardPublic,
    UserDashboardBlock,
    UserDashboardBlockCreate,
    UserDashboardBlockUpdate,
    UserDashboardBlockPublic,
    BlockLayoutUpdate,
    UserDashboardBlockPromptAction,
    UserDashboardBlockPromptActionCreate,
    UserDashboardBlockPromptActionUpdate,
    UserDashboardBlockPromptActionPublic,
)
from .cli.cli_setup_token import (
    CLISetupToken,
    CLISetupTokenBase,
    CLISetupTokenCreate,
    CLISetupTokenPublic,
    CLISetupTokenCreated,
)
from .cli.cli_token import (
    CLIToken,
    CLITokenBase,
    CLITokenCreate,
    CLITokenPublic,
    CLITokenCreated,
    CLITokensPublic,
    CLITokenPayload,
)
from .agentic_teams.agentic_team import (
    AgenticTeam,
    AgenticTeamCreate,
    AgenticTeamUpdate,
    AgenticTeamPublic,
    AgenticTeamsPublic,
    AgenticTeamNode,
    AgenticTeamNodeCreate,
    AgenticTeamNodeUpdate,
    AgenticTeamNodePublic,
    AgenticTeamNodesPublic,
    AgenticTeamNodePositionUpdate,
    AgenticTeamConnection,
    AgenticTeamConnectionCreate,
    AgenticTeamConnectionUpdate,
    AgenticTeamConnectionPublic,
    AgenticTeamConnectionsPublic,
    AgenticTeamChartPublic,
    GenerateConnectionPromptResponse,
)
from .app_mcp.app_agent_route import (
    AppAgentRoute,
    AppAgentRouteAssignment,
    UserAppAgentRoute,
    AppAgentRouteCreate,
    AppAgentRouteUpdate,
    AppAgentRoutePublic,
    AppAgentRouteAssignmentPublic,
    RouteConflictMatch,
    RouteConflictResponse,
    UserAppAgentRouteCreate,
    UserAppAgentRouteUpdate,
    UserAppAgentRoutePublic,
    SharedRoutePublic,
    UserAppAgentRoutesResponse,
)
from .app_mcp.app_mcp_token import AppMCPToken
from .app_mcp.app_mcp_oauth_client import (
    AppMCPOAuthClient,
    AppMCPOAuthClientPublic,
)
from .app_mcp.app_mcp_auth_code import (
    AppMCPAuthCode,
    AppMCPAuthRequest,
)
from .identity.identity_models import (
    IdentityAgentBinding,
    IdentityBindingAssignment,
    IdentityAgentBindingCreate,
    IdentityAgentBindingUpdate,
    IdentityBindingAssignmentPublic,
    IdentityAgentBindingPublic,
    IdentityContactPublic,
)
from .desktop_auth.desktop_oauth_client import (
    DesktopOAuthClient,
    DesktopOAuthClientCreate,
    DesktopOAuthClientPublic,
)
from .desktop_auth.desktop_refresh_token import DesktopRefreshToken
from .desktop_auth.desktop_auth_code import DesktopAuthCode
from .desktop_auth.desktop_auth_request import DesktopAuthRequest
from .app_sync.app_sync_record import AppSyncRecord
from .app_sync.app_sync_state import AppSyncState
from .app_sync.app_sync_device import (
    AppSyncDevice,
    AppSyncDeviceCreate,
    AppSyncDevicePublic,
)
from .app_sync.app_sync_key_envelope import (
    AppSyncKeyEnvelope,
    AppSyncKeyEnvelopeCreate,
    AppSyncKeyEnvelopePublic,
)
from .app_sync.app_sync_pairing import (
    AppSyncPairing,
    PairingStartRequest,
    PairingStartResponse,
    PairingStatusPublic,
    PairingCompleteRequest,
    PairingSealerNonceRequest,
    PairingRevealRequest,
    PairingInboxItem,
    PairingInboxDetail,
)
from .app_sync.app_sync_schemas import (
    SyncRecordUpsert,
    SyncRecordPublic,
    SyncPushResult,
    SyncRequest,
    PullRequest,
    PushRequest,
    WipeRequest,
    SyncResponse,
    SyncStatePublic,
    EncryptionStatePublic,
    KeyEnvelopeInput,
    DeviceInput,
    EncryptionInitRequest,
)
from .external.external_agents import (
    ExternalTargetPublic,
    ExternalAgentListResponse,
    ExternalSessionPublic,
)
from .bundles.app_data_volume import (
    AppDataVolume,
    AppDataVolumePublic,
    AppDataVolumesPublic,
)
from .notifications.user_notification_setting import (
    UserNotificationSetting,
    UserNotificationSettingUpdate,
    NotificationSettingItem,
    NotificationSettingsPublic,
)

__all__ = [
    # Core
    "SQLModel",
    # Link models
    "AgentCredentialLink",
    # Users
    "User",
    "UserCreate",
    "UserRegister",
    "UserUpdate",
    "UserUpdateMe",
    "UserPublic",
    "UsersPublic",
    "UserSearchResult",
    "UsersSearchPublic",
    "UpdatePassword",
    "Message",
    "NewPassword",
    "Token",
    "TokenPayload",
    "SetPassword",
    "OAuthConfig",
    # Two-Factor Authentication (MFA)
    "UserPasskey",
    "UserPasskeyPublic",
    "UserPasskeysPublic",
    "UserPasskeyUpdate",
    "UserTotpSecret",
    "TotpEnrollResponse",
    "TotpFinishRequest",
    "UserRecoveryCode",
    "RecoveryCodeStatus",
    "RecoveryCodesPlaintext",
    "UserTrustedDevice",
    "TrustedDevicePublic",
    "UserMfaChallenge",
    "MfaFirstFactor",
    "MfaChallenge",
    "MfaVerifyRequest",
    "LoginToken",
    "LoginResponse",
    "MfaStatus",
    "StepUpProof",
    "PasskeyAuthOptionsRequest",
    "PasskeyAuthOptionsResponse",
    # Agents
    "Agent",
    "AgentCreate",
    "AgentUpdate",
    "AgentPublic",
    "AgentsPublic",
    "AgentCredentialLink",
    "AgentWithCredentials",
    "AgentCredentialLinkRequest",
    "AgentCreateFlowRequest",
    "AgentCreateFlowResponse",
    "AgentSdkConfig",
    "AllowedToolsUpdate",
    "PendingToolsResponse",
    "GenerateRouterTriggerPromptResponse",
    "RouterTriggerPromptUpdate",
    "UpdateMode",
    # Credentials
    "Credential",
    "CredentialCreate",
    "CredentialUpdate",
    "CredentialPublic",
    "CredentialsPublic",
    "CredentialBundleUsage",
    "CredentialBundleUsages",
    "CredentialAffectedAgent",
    "CredentialDeletionImpact",
    "CredentialType",
    "EmailImapData",
    "OdooData",
    "GmailOAuthData",
    "ApiTokenData",
    "SSHKeyCredentialData",
    "CredentialWithData",
    # AI Credentials
    "AICredential",
    "AICredentialCreate",
    "AICredentialUpdate",
    "AICredentialPublic",
    "AICredentialBundleUsage",
    "AICredentialDeletionImpact",
    "AICredentialsPublic",
    "AICredentialType",
    "AICredentialData",
    # AI Credential Shares
    "AICredentialShare",
    "AICredentialShareBase",
    "AICredentialSharePublic",
    "AICredentialShareCreate",
    "AICredentialSharesPublic",
    "SharedAICredentialPublic",
    "SharedAICredentialsPublic",
    # Credential Shares
    "CredentialShare",
    "CredentialShareBase",
    "CredentialSharePublic",
    "CredentialShareCreate",
    "CredentialSharesPublic",
    "SharedCredentialPublic",
    "SharedCredentialsPublic",
    # Agent Bundles (Phase 2)
    "AgentBundle",
    "AgentBundleBase",
    "AgentBundlePublic",
    "AgentBundlesPublic",
    "AgentBundleUpdate",
    "BundleVisibility",
    "BundleInstallMode",
    # Agent Bundle Revisions
    "AgentBundleRevision",
    "AgentBundleRevisionPublic",
    "AgentBundleRevisionsPublic",
    "PublishRequest",
    # Bundle Access Grants
    "BundleAccessGrant",
    "BundleAccessGrantPublic",
    "BundleAccessGrantsPublic",
    "BundleAccessGrantCreate",
    # Catalog & install schemas
    "CatalogEntryPublic",
    "CatalogPublic",
    "AICredentialSelections",
    "InstallRequest",
    "InstallCredentialSelection",
    "AdminInstallRequest",
    "SetUpdateModeRequest",
    "EditBundleIdRequest",
    "CheckUpdatesResponse",
    "CatalogInstallContext",
    "InstallContextSpec",
    "InstallContextAIPublisherSummaries",
    "InstallContextPublisherSummary",
    "CredentialSpecDrift",
    "BundleCredentialDrift",
    # Environments
    "AgentEnvironment",
    "AgentEnvironmentCreate",
    "AgentEnvironmentUpdate",
    "AgentEnvironmentReconfigure",
    "AgentEnvironmentPublic",
    "AgentEnvironmentsPublic",
    # Admin Environments (admin-only schemas)
    "AdminAgentEnvironmentPublic",
    "AdminAgentEnvironmentsPublic",
    "AdminTemplateInfoPublic",
    "AdminBulkSkipped",
    "AdminBulkRebuildRequest",
    "AdminBulkRebuildResponse",
    # Sessions
    "Session",
    "SessionCreate",
    "SessionUpdate",
    "SessionPublic",
    "SessionPublicExtended",
    "SessionsPublic",
    "SessionsPublicExtended",
    # Messages
    "SessionMessage",
    "MessageCreate",
    "MessagePublic",
    "MessagesPublic",
    "SessionCommandPublic",
    "SessionCommandsPublic",
    # Session Sender (Channel Ingestion Service value types)
    "SessionSender",
    "SessionSenderKind",
    "ChannelAccessPolicy",
    "IngestionResult",
    "get_session_sender",
    # Activities
    "Activity",
    "ActivityCreate",
    "ActivityUpdate",
    "ActivityPublic",
    "ActivityPublicExtended",
    "ActivitiesPublic",
    "ActivitiesPublicExtended",
    "ActivityStats",
    # Events
    "EventType",
    "EventBase",
    "EventPublic",
    "EventBroadcast",
    "ConnectionInfo",
    # Agent Schedules
    "AgentSchedule",
    "ScheduleRequest",
    "ScheduleResponse",
    "CreateScheduleRequest",
    "UpdateScheduleRequest",
    "AgentSchedulePublic",
    "AgentSchedulesPublic",
    # Agent Schedule Logs
    "AgentScheduleLog",
    "AgentScheduleLogPublic",
    "AgentScheduleLogsPublic",
    # Agent Webhooks
    "AgentWebhook",
    "AgentWebhookType",
    "AgentWebhookCreateSession",
    "AgentWebhookCreateScript",
    "AgentWebhookUpdate",
    "AgentWebhookPublic",
    "AgentWebhookPublicWithToken",
    "AgentWebhooksPublic",
    # Agent Webhook Logs
    "AgentWebhookLog",
    "AgentWebhookLogPublic",
    "AgentWebhookLogsPublic",
    # Agent Handovers / Task Creation
    "AgentHandoverConfig",
    "HandoverConfigCreate",
    "HandoverConfigUpdate",
    "HandoverConfigPublic",
    "HandoverConfigsPublic",
    "GenerateHandoverPromptRequest",
    "GenerateHandoverPromptResponse",
    "CreateAgentTaskRequest",
    "CreateAgentTaskResponse",
    "ExecuteHandoverRequest",  # Deprecated
    "ExecuteHandoverResponse",  # Deprecated
    "UpdateSessionStateRequest",
    "UpdateSessionStateResponse",
    "RespondToTaskRequest",
    # User Workspaces
    "UserWorkspace",
    "UserWorkspaceCreate",
    "UserWorkspaceUpdate",
    "UserWorkspacePublic",
    "UserWorkspacesPublic",
    # SSH Keys
    "UserSSHKey",
    "SSHKeyGenerate",
    "SSHKeyImport",
    "SSHKeyPublic",
    "SSHKeysPublic",
    "SSHKeyUpdate",
    # Knowledge Management
    "AIKnowledgeGitRepo",
    "AIKnowledgeGitRepoCreate",
    "AIKnowledgeGitRepoUpdate",
    "AIKnowledgeGitRepoPublic",
    "AIKnowledgeGitRepoWorkspace",
    "UserEnabledDiscoverableSource",
    "DiscoverableSourcePublic",
    "KnowledgeArticle",
    "KnowledgeArticlePublic",
    "KnowledgeArticleDetail",
    "KnowledgeArticleChunk",
    "KnowledgeArticleChunkPublic",
    "SourceStatus",
    "WorkspaceAccessType",
    "CheckAccessResponse",
    "RefreshKnowledgeResponse",
    "ArticleListItem",
    "ArticleContent",
    # LLM Plugin Management
    "LLMPluginMarketplace",
    "LLMPluginMarketplaceCreate",
    "LLMPluginMarketplaceUpdate",
    "LLMPluginMarketplacePublic",
    "LLMPluginMarketplacesPublic",
    "LLMPluginMarketplacePlugin",
    "LLMPluginMarketplacePluginPublic",
    "LLMPluginMarketplacePluginsPublic",
    "AgentPluginLink",
    "AgentPluginLinkCreate",
    "AgentPluginLinkUpdate",
    "AgentPluginLinkPublic",
    "AgentPluginLinkWithPlugin",
    "AgentPluginLinkWithUpdateInfo",
    "AgentPluginLinksPublic",
    "MarketplaceStatus",
    "PluginSourceType",
    # Agent Access Tokens
    "AgentAccessToken",
    "AgentAccessTokenCreate",
    "AgentAccessTokenUpdate",
    "AgentAccessTokenPublic",
    "AgentAccessTokenCreated",
    "AgentAccessTokensPublic",
    "AccessTokenMode",
    "AccessTokenScope",
    "A2ATokenPayload",
    # Agent REST API Tokens
    "AgentApiToken",
    "AgentApiTokenBase",
    "AgentApiTokenCreate",
    "AgentApiTokenPublic",
    "AgentApiTokenCreated",
    "AgentApiConnectedAgent",
    "AgentApiConnectionInfo",
    "AgentApiProducerConnection",
    "AgentApiProducerConnections",
    "ConnectAgentApiRequest",
    "ConnectAgentApiResponse",
    # Agent Guest Shares
    "AgentGuestShare",
    "AgentGuestShareBase",
    "AgentGuestShareCreate",
    "AgentGuestShareUpdate",
    "AgentGuestSharePublic",
    "AgentGuestShareCreated",
    "AgentGuestSharesPublic",
    "GuestShareGrant",
    "GuestShareTokenPayload",
    # Input Tasks
    "InputTask",
    "InputTaskCreate",
    "InputTaskUpdate",
    "InputTaskPublic",
    "InputTaskPublicExtended",
    "InputTaskDetailPublic",
    "InputTasksPublic",
    "InputTasksPublicExtended",
    "InputTaskStatus",
    "RefinementHistoryItem",
    "RefineTaskRequest",
    "RefineTaskResponse",
    "ExecuteTaskRequest",
    "ExecuteTaskResponse",
    "SendAnswerRequest",
    "SendAnswerResponse",
    "AgentTaskStatusUpdate",
    "AgentSubtaskCreate",
    "AgentTaskCreate",
    "AgentTaskOperationResponse",
    # Task Comments
    "TaskComment",
    "TaskCommentBase",
    "TaskCommentCreate",
    "AgentTaskCommentCreate",
    "TaskCommentPublic",
    "TaskCommentsPublic",
    # Task Attachments
    "TaskAttachment",
    "TaskAttachmentBase",
    "TaskAttachmentPublic",
    "TaskAttachmentsPublic",
    # Task Status History
    "TaskStatusHistory",
    "TaskStatusHistoryPublic",
    "TaskStatusHistoriesPublic",
    # Task Triggers
    "TaskTrigger",
    "TriggerType",
    "TaskTriggerCreateSchedule",
    "TaskTriggerCreateExactDate",
    "TaskTriggerCreateWebhook",
    "TaskTriggerUpdate",
    "TaskTriggerPublic",
    "TaskTriggerPublicWithToken",
    "TaskTriggersPublic",
    # Agent Email Integration
    "AgentEmailIntegration",
    "AgentEmailIntegrationCreate",
    "AgentEmailIntegrationUpdate",
    "AgentEmailIntegrationPublic",
    "EmailAccessMode",
    "EmailCloneShareMode",
    "EmailProcessAs",
    "ProcessEmailsResult",
    # Mail Server Config
    "MailServerConfig",
    "MailServerConfigCreate",
    "MailServerConfigUpdate",
    "MailServerConfigPublic",
    "MailServerConfigsPublic",
    "MailServerType",
    "EncryptionType",
    # Email Messages
    "EmailMessage",
    "EmailMessagePublic",
    # Outgoing Email Queue
    "OutgoingEmailQueue",
    "OutgoingEmailQueuePublic",
    "OutgoingEmailStatus",
    # MCP Connectors
    "MCPConnector",
    "MCPConnectorCreate",
    "MCPConnectorUpdate",
    "MCPConnectorPublic",
    "MCPConnectorsPublic",
    # MCP OAuth
    "MCPOAuthClient",
    "MCPOAuthClientPublic",
    "MCPAuthCode",
    "MCPAuthRequest",
    "MCPToken",
    # MCP Session Meta
    "MCPSessionMeta",
    "MCPSessionMetaPublic",
    # MCP Transport Sessions
    "MCPTransportSession",
    # Agent Webapp Shares
    "AgentWebappShare",
    "AgentWebappShareBase",
    "AgentWebappShareCreate",
    "AgentWebappShareUpdate",
    "AgentWebappSharePublic",
    "AgentWebappShareCreated",
    "AgentWebappSharesPublic",
    "WebappShareTokenPayload",
    # Agent Webapp Interface Config
    "AgentWebappInterfaceConfig",
    "AgentWebappInterfaceConfigBase",
    "AgentWebappInterfaceConfigCreate",
    "AgentWebappInterfaceConfigUpdate",
    "AgentWebappInterfaceConfigPublic",
    # Security Events
    "SecurityEvent",
    "SecurityEventCreate",
    "SecurityEventPublic",
    "SecurityEventsPublic",
    "CREDENTIAL_READ_ATTEMPT",
    "CREDENTIAL_BASH_ACCESS",
    "OUTPUT_REDACTED",
    "CREDENTIAL_WRITE_ATTEMPT",
    "MFA_ENROLLED",
    "MFA_DISABLED",
    "MFA_CHALLENGE_ISSUED",
    "MFA_CHALLENGE_SUCCESS",
    "MFA_CHALLENGE_FAILED",
    "MFA_RECOVERY_CODE_USED",
    "MFA_RATE_LIMITED",
    "MFA_SIGN_COUNT_REGRESSION",
    "MFA_PASSKEY_INVALID_ORIGIN",
    "MFA_RECOVERY_CODES_REGENERATED",
    # User Dashboards
    "UserDashboard",
    "UserDashboardCreate",
    "UserDashboardUpdate",
    "UserDashboardPublic",
    "UserDashboardBlock",
    "UserDashboardBlockCreate",
    "UserDashboardBlockUpdate",
    "UserDashboardBlockPublic",
    "BlockLayoutUpdate",
    "UserDashboardBlockPromptAction",
    "UserDashboardBlockPromptActionCreate",
    "UserDashboardBlockPromptActionUpdate",
    "UserDashboardBlockPromptActionPublic",
    # AgenticTeams
    "AgenticTeam",
    "AgenticTeamCreate",
    "AgenticTeamUpdate",
    "AgenticTeamPublic",
    "AgenticTeamsPublic",
    "AgenticTeamNode",
    "AgenticTeamNodeCreate",
    "AgenticTeamNodeUpdate",
    "AgenticTeamNodePublic",
    "AgenticTeamNodesPublic",
    "AgenticTeamNodePositionUpdate",
    "AgenticTeamConnection",
    "AgenticTeamConnectionCreate",
    "AgenticTeamConnectionUpdate",
    "AgenticTeamConnectionPublic",
    "AgenticTeamConnectionsPublic",
    "AgenticTeamChartPublic",
    "GenerateConnectionPromptResponse",
    # App MCP Server — Route Models
    "AppAgentRoute",
    "AppAgentRouteAssignment",
    "UserAppAgentRoute",
    "AppAgentRouteCreate",
    "AppAgentRouteUpdate",
    "AppAgentRoutePublic",
    "AppAgentRouteAssignmentPublic",
    "RouteConflictMatch",
    "RouteConflictResponse",
    "UserAppAgentRouteCreate",
    "UserAppAgentRouteUpdate",
    "UserAppAgentRoutePublic",
    "SharedRoutePublic",
    "UserAppAgentRoutesResponse",
    # App MCP Server — Token & OAuth
    "AppMCPToken",
    "AppMCPOAuthClient",
    "AppMCPOAuthClientPublic",
    "AppMCPAuthCode",
    "AppMCPAuthRequest",
    # Identity MCP Server
    "IdentityAgentBinding",
    "IdentityBindingAssignment",
    "IdentityAgentBindingCreate",
    "IdentityAgentBindingUpdate",
    "IdentityBindingAssignmentPublic",
    "IdentityAgentBindingPublic",
    "IdentityContactPublic",
    # Desktop Auth
    "DesktopOAuthClient",
    "DesktopOAuthClientCreate",
    "DesktopOAuthClientPublic",
    "DesktopRefreshToken",
    "DesktopAuthCode",
    "DesktopAuthRequest",
    # App Sync
    "AppSyncRecord",
    "AppSyncState",
    "AppSyncDevice",
    "AppSyncDeviceCreate",
    "AppSyncDevicePublic",
    "AppSyncKeyEnvelope",
    "AppSyncKeyEnvelopeCreate",
    "AppSyncKeyEnvelopePublic",
    "AppSyncPairing",
    "PairingStartRequest",
    "PairingStartResponse",
    "PairingStatusPublic",
    "PairingCompleteRequest",
    "PairingSealerNonceRequest",
    "PairingRevealRequest",
    "PairingInboxItem",
    "PairingInboxDetail",
    "SyncRecordUpsert",
    "SyncRecordPublic",
    "SyncPushResult",
    "SyncRequest",
    "PullRequest",
    "PushRequest",
    "WipeRequest",
    "SyncResponse",
    "SyncStatePublic",
    "EncryptionStatePublic",
    "KeyEnvelopeInput",
    "DeviceInput",
    "EncryptionInitRequest",
    # External Agent Access API
    "ExternalTargetPublic",
    "ExternalAgentListResponse",
    "ExternalSessionPublic",
    # App Data Volumes (Phase 1: agent bundles & installs)
    "AppDataVolume",
    "AppDataVolumePublic",
    "AppDataVolumesPublic",
    # System Notifications
    "UserNotificationSetting",
    "UserNotificationSettingUpdate",
    "NotificationSettingItem",
    "NotificationSettingsPublic",
]
