"""add_agent_environment_skills_cache

Adds the four pull-only cache columns ``AgentSkillsService`` writes: the parsed
skill index, the ``skills/`` tree hash it short-circuits on, when it was last
read, and why the last read failed. All nullable — NULL means "never read",
which is exactly what an environment that predates the feature is.

The autogenerated ``cli_device_login_request`` timezone alterations were
removed by hand: they are pre-existing model/DB drift unrelated to this change,
and carrying them here would make an unrelated rollback impossible.

Revision ID: 08e5661b36ed
Revises: 45938a69aee7
Create Date: 2026-09-08 13:25:52.941734

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '08e5661b36ed'
down_revision = '45938a69aee7'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        'agent_environment',
        sa.Column('skills_parsed', sa.JSON(), nullable=True),
    )
    op.add_column(
        'agent_environment',
        sa.Column('skills_hash', sa.String(length=64), nullable=True),
    )
    op.add_column(
        'agent_environment',
        sa.Column('skills_fetched_at', sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        'agent_environment',
        sa.Column('skills_error', sa.String(length=256), nullable=True),
    )


def downgrade():
    op.drop_column('agent_environment', 'skills_error')
    op.drop_column('agent_environment', 'skills_fetched_at')
    op.drop_column('agent_environment', 'skills_hash')
    op.drop_column('agent_environment', 'skills_parsed')
