"""add mcp_session_meta table

Revision ID: 1cfe565b5e39
Revises: a4c8d9e0f1b2
Create Date: 2026-03-02 08:52:03.586372

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1cfe565b5e39'
down_revision = 'a4c8d9e0f1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_session_meta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('authenticated_user_id', sa.Uuid(), nullable=False),
    sa.Column('authenticated_user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connector_id', sa.Uuid(), nullable=False),
    sa.Column('oauth_client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['authenticated_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['connector_id'], ['mcp_connector.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_session_meta_session_id'), 'mcp_session_meta', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mcp_session_meta_session_id'), table_name='mcp_session_meta')
    op.drop_table('mcp_session_meta')
    # ### end Alembic commands ###
