"""add agent_api_access_grant table and agent_api_identity_enabled flag

Revision ID: 25a74abc7f4a
Revises: c70a14722869
Create Date: 2026-06-20 21:53:49.300401

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = '25a74abc7f4a'
down_revision = 'c70a14722869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_api_access_grant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('producer_agent_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producer_agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producer_agent_id', 'user_id', name='uq_agent_api_access_grant_producer_user')
    )
    op.create_index(op.f('ix_agent_api_access_grant_producer_agent_id'), 'agent_api_access_grant', ['producer_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_api_access_grant_user_id'), 'agent_api_access_grant', ['user_id'], unique=False)
    # New NOT NULL boolean: add with a server_default so existing agent rows
    # backfill to False, then drop the default so the application-level default
    # (Field(default=False)) is the source of truth going forward.
    op.add_column(
        'agent',
        sa.Column(
            'agent_api_identity_enabled',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.alter_column('agent', 'agent_api_identity_enabled', server_default=None)
    # NOTE: hand-trimmed unrelated autogen drift on `cli_device_login_request`
    # (pre-existing TIMESTAMP→DateTime diff not introduced by this change).
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'agent_api_identity_enabled')
    op.drop_index(op.f('ix_agent_api_access_grant_user_id'), table_name='agent_api_access_grant')
    op.drop_index(op.f('ix_agent_api_access_grant_producer_agent_id'), table_name='agent_api_access_grant')
    op.drop_table('agent_api_access_grant')
    # ### end Alembic commands ###
