"""add_bundle_revision_skills_summary

Adds the derived ``skills_summary`` column to ``agent_bundle_revision``:
``[{name, description, has_scripts}]``, computed at publish from the snapshot's
``skills/`` tree and never authored by a publisher.

Nullable with no backfill on purpose. NULL means "this revision predates agent
skills", which the restore side must treat as "do not touch"; ``[]`` means "the
publisher's agent had no skills". Backfilling would erase that distinction.

The autogenerated ``cli_device_login_request`` timezone alterations were
removed by hand: pre-existing model/DB drift, unrelated to this change.

Revision ID: 2affe6c57bf7
Revises: 08e5661b36ed
Create Date: 2026-09-08 13:30:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2affe6c57bf7'
down_revision = '08e5661b36ed'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        'agent_bundle_revision',
        sa.Column('skills_summary', sa.JSON(), nullable=True),
    )


def downgrade():
    op.drop_column('agent_bundle_revision', 'skills_summary')
