"""add_caller_id_to_session

Revision ID: 2c222ba66e57
Revises: b5a73df91425
Create Date: 2026-04-16 13:18:47.899694

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2c222ba66e57'
down_revision = 'b5a73df91425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('caller_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_session_caller_id'), 'session', ['caller_id'], unique=False)
    op.create_foreign_key(None, 'session', 'user', ['caller_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # Backfill: for existing app_mcp sessions, move user_id → caller_id and
    # set user_id to the agent owner's ID so the owner sees these sessions.
    op.execute("""
        UPDATE session
        SET caller_id = user_id,
            user_id = (SELECT owner_id FROM agent WHERE agent.id = session.agent_id)
        WHERE integration_type = 'app_mcp'
          AND agent_id IS NOT NULL
    """)


def downgrade():
    # Reverse backfill: restore caller_id → user_id for app_mcp sessions before dropping column.
    op.execute("""
        UPDATE session
        SET user_id = caller_id
        WHERE integration_type = 'app_mcp'
          AND caller_id IS NOT NULL
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_index(op.f('ix_session_caller_id'), table_name='session')
    op.drop_column('session', 'caller_id')
    # ### end Alembic commands ###
