"""add agent_git_source

Revision ID: 391a6285d8ff
Revises: b2d1f4c6a8e3
Create Date: 2026-06-27 15:12:51.493075

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = '391a6285d8ff'
down_revision = 'b2d1f4c6a8e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_git_source',
    sa.Column('repo_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('subdir', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('ref', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('ssh_key_id', sa.Uuid(), nullable=True),
    sa.Column('sync_direction', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('bundle_uuid', sa.Uuid(), nullable=True),
    sa.Column('last_synced_commit', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bundle_uuid'], ['agent_bundle.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ssh_key_id'], ['user_ssh_keys.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_git_source_agent_id', 'agent_git_source', ['agent_id'], unique=True)
    op.create_index('ix_agent_git_source_owner_id', 'agent_git_source', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_git_source_owner_id', table_name='agent_git_source')
    op.drop_index('ix_agent_git_source_agent_id', table_name='agent_git_source')
    op.drop_table('agent_git_source')
    # ### end Alembic commands ###
