"""add user workspaces support

Revision ID: 3a154fd039f5
Revises: b26f2c36507c
Create Date: 2026-01-03 13:10:11.207201

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3a154fd039f5'
down_revision = 'b26f2c36507c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_workspace',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('activity', sa.Column('user_workspace_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'activity', 'user_workspace', ['user_workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('agent', sa.Column('user_workspace_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'agent', 'user_workspace', ['user_workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('credential', sa.Column('user_workspace_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'credential', 'user_workspace', ['user_workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('session', sa.Column('user_workspace_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'session', 'user_workspace', ['user_workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_column('session', 'user_workspace_id')
    op.drop_constraint(None, 'credential', type_='foreignkey')
    op.drop_column('credential', 'user_workspace_id')
    op.drop_constraint(None, 'agent', type_='foreignkey')
    op.drop_column('agent', 'user_workspace_id')
    op.drop_constraint(None, 'activity', type_='foreignkey')
    op.drop_column('activity', 'user_workspace_id')
    op.drop_table('user_workspace')
    # ### end Alembic commands ###
