"""add show_on_dashboard to agent

Revision ID: 3b9c8d4e5f6a
Revises: 8510f306b385
Create Date: 2026-01-08 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b9c8d4e5f6a'
down_revision = '8510f306b385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('show_on_dashboard', sa.Boolean(), nullable=True))
    # Set default value for existing agents (show on dashboard by default)
    op.execute("UPDATE agent SET show_on_dashboard = true WHERE show_on_dashboard IS NULL")
    # Make the column non-nullable after setting defaults
    op.alter_column('agent', 'show_on_dashboard', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'show_on_dashboard')
    # ### end Alembic commands ###
