"""channel visibility grants and per-user settings

Revision ID: 458913091bd5
Revises: 1f9f81b0bb79
Create Date: 2026-08-24 18:35:47.000000

Phase 2 of the channels & identity unification: the admin-owned availability
model and the per-user settings model.

Adds three tables — ``server_channel_user_grant``, ``channel_user_setting``,
``channel_user_agent`` — and four policy columns on ``server_channel``.

HAND-CORRECTED AFTER AUTOGENERATE. Four notes:

1. **The four ``server_channel`` columns are NOT NULL and the table has rows.**
   Each is added with a server default that reproduces today's behaviour
   exactly — ``visibility='public'``, ``default_enabled_for_users=true``,
   ``default_agent_scope='all'``, ``allow_auto_install=true`` — so an existing
   channel comes out of this migration behaving identically to before it. The
   defaults are then dropped, so the application (not the schema) owns the
   value for new rows; the same shape as ``cdfb21cadb62``.

2. **``channel_user_setting.is_enabled`` and ``.agent_scope`` stay nullable
   with NO server default.** Autogenerate got this right and it must stay
   right: NULL means "inherit the channel default", and a server default would
   silently convert every future row into a frozen explicit choice. See the
   model's docstring. ``allow_identity_routing`` is the deliberate exception —
   NOT NULL DEFAULT false, kept, because it never inherits (master plan §3.4).

3. **The new tables' timestamps are naive (``TIMESTAMP WITHOUT TIME ZONE``),
   deliberately.** That is this codebase's convention — ``server_channel`` and
   ``channel_thread_binding`` are the same, and ``ServerChannelService._as_utc``
   exists to reconcile it — not the ``timestamptz`` the plan's table sketch
   writes. The models stamp aware ``datetime.now(UTC)`` and Postgres hands the
   value back naive, so comparing a read-back ``updated_at`` against an aware
   ``now()`` raises. Normalise before comparing.

4. **Three ``cli_device_login_request`` timestamp alterations were removed.**
   Autogenerate proposes them on every run: the model declares bare
   ``datetime`` while the column is ``TIMESTAMP WITH TIME ZONE``. The database
   is right and the model is wrong; "fixing" the database here would drop the
   timezone off live rows for an unrelated feature.
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = '458913091bd5'
down_revision = '1f9f81b0bb79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_user_setting',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('server_channel_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    # nullable=True with NO server_default, on purpose: NULL means "inherit the
    # channel default". Adding a server default here would freeze every row
    # against a later change of that default. Do not "tidy" these.
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('agent_scope', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('pinned_agent_id', sa.Uuid(), nullable=True),
    # NOT NULL DEFAULT false, and the default is KEPT: this column never
    # inherits from the channel, so 'off' is its meaning, not a placeholder.
    sa.Column('allow_identity_routing', sa.Boolean(), nullable=False,
              server_default=sa.false()),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pinned_agent_id'], ['agent.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_channel_id'], ['server_channel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_channel_id', 'user_id', name='uq_channel_user_setting')
    )
    op.create_index(op.f('ix_channel_user_setting_user_id'), 'channel_user_setting', ['user_id'], unique=False)
    op.create_table('server_channel_user_grant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('server_channel_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('granted_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_channel_id'], ['server_channel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_channel_id', 'user_id', name='uq_server_channel_user_grant')
    )
    op.create_index(op.f('ix_server_channel_user_grant_user_id'), 'server_channel_user_grant', ['user_id'], unique=False)
    op.create_table('channel_user_agent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_user_setting_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['channel_user_setting_id'], ['channel_user_setting.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_user_setting_id', 'agent_id', name='uq_channel_user_agent')
    )
    op.create_index(op.f('ix_channel_user_agent_agent_id'), 'channel_user_agent', ['agent_id'], unique=False)
    # The four policy columns. NOT NULL on a table that already has rows, so
    # each carries a server default long enough to backfill. Every default is
    # chosen to leave an existing channel behaving exactly as it did before
    # this phase: visible to everyone, on for everyone, every owned agent a
    # candidate, and Pass 2 auto-install still running.
    op.add_column('server_channel', sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False, server_default='public'))
    op.add_column('server_channel', sa.Column('default_enabled_for_users', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('server_channel', sa.Column('default_agent_scope', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False, server_default='all'))
    op.add_column('server_channel', sa.Column('allow_auto_install', sa.Boolean(), nullable=False, server_default=sa.true()))

    # Drop the defaults now the backfill is done: the application supplies these
    # on every insert, and a schema-level default would quietly paper over a
    # future create path that forgot one.
    #
    # ``server_default=None`` really does emit DROP DEFAULT: Alembic's sentinel
    # for "not specified" on this parameter is ``False``, not ``None``. It reads
    # like a no-op and is not one.
    op.alter_column('server_channel', 'visibility',
                    existing_type=sqlmodel.sql.sqltypes.AutoString(length=32),
                    existing_nullable=False, server_default=None)
    op.alter_column('server_channel', 'default_enabled_for_users',
                    existing_type=sa.Boolean(),
                    existing_nullable=False, server_default=None)
    op.alter_column('server_channel', 'default_agent_scope',
                    existing_type=sqlmodel.sql.sqltypes.AutoString(length=32),
                    existing_nullable=False, server_default=None)
    op.alter_column('server_channel', 'allow_auto_install',
                    existing_type=sa.Boolean(),
                    existing_nullable=False, server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server_channel', 'allow_auto_install')
    op.drop_column('server_channel', 'default_agent_scope')
    op.drop_column('server_channel', 'default_enabled_for_users')
    op.drop_column('server_channel', 'visibility')
    op.drop_index(op.f('ix_channel_user_agent_agent_id'), table_name='channel_user_agent')
    op.drop_table('channel_user_agent')
    op.drop_index(op.f('ix_server_channel_user_grant_user_id'), table_name='server_channel_user_grant')
    op.drop_table('server_channel_user_grant')
    op.drop_index(op.f('ix_channel_user_setting_user_id'), table_name='channel_user_setting')
    op.drop_table('channel_user_setting')
    # ### end Alembic commands ###
