"""add email_message table

Revision ID: 485e7e243dd5
Revises: 7aeed6ea3abf
Create Date: 2026-02-12 16:58:40.632460

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '485e7e243dd5'
down_revision = '7aeed6ea3abf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_message',
    sa.Column('email_message_id', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('sender', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('in_reply_to', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('clone_agent_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('pending_clone_creation', sa.Boolean(), nullable=False),
    sa.Column('attachments_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['clone_agent_id'], ['agent.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_message')
    # ### end Alembic commands ###
