"""add_security_event_table

Revision ID: 5432134b1366
Revises: a7v8w9x0y1z2
Create Date: 2026-03-09 12:33:16.161080

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5432134b1366'
down_revision = 'a7v8w9x0y1z2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('environment_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('guest_share_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['environment_id'], ['agent_environment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guest_share_id'], ['agent_guest_share.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Indexes for security_event table
    op.create_index('ix_security_event_user_id', 'security_event', ['user_id'])
    op.create_index('ix_security_event_agent_id', 'security_event', ['agent_id'])
    op.create_index('ix_security_event_session_id', 'security_event', ['session_id'])
    op.create_index('ix_security_event_event_type', 'security_event', ['event_type'])
    op.create_index('ix_security_event_created_at', 'security_event', ['created_at'])
    op.create_index(
        'ix_security_event_guest_share_created',
        'security_event',
        ['guest_share_id', 'created_at'],
    )
    op.alter_column('mcp_transport_session', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('ix_session_webapp_share_id'), table_name='session')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_session_webapp_share_id'), 'session', ['webapp_share_id'], unique=False)
    op.alter_column('mcp_transport_session', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # Drop indexes before table
    op.drop_index('ix_security_event_guest_share_created', 'security_event')
    op.drop_index('ix_security_event_created_at', 'security_event')
    op.drop_index('ix_security_event_event_type', 'security_event')
    op.drop_index('ix_security_event_session_id', 'security_event')
    op.drop_index('ix_security_event_agent_id', 'security_event')
    op.drop_index('ix_security_event_user_id', 'security_event')
    op.drop_table('security_event')
    # ### end Alembic commands ###
