"""add ui_color_preset to agent

Revision ID: 57b4e9d8707e
Revises: cc18aee3c7c4
Create Date: 2025-12-26 10:51:29.342172

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '57b4e9d8707e'
down_revision = 'cc18aee3c7c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('ui_color_preset', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # Set default value for existing agents
    op.execute("UPDATE agent SET ui_color_preset = 'slate' WHERE ui_color_preset IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'ui_color_preset')
    # ### end Alembic commands ###
