"""add share source and session email fields

Revision ID: 7aeed6ea3abf
Revises: cc1e27a71798
Create Date: 2026-02-12 16:49:51.411570

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7aeed6ea3abf'
down_revision = 'cc1e27a71798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_share', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='manual'))
    op.add_column('session', sa.Column('email_thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('session', sa.Column('integration_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'integration_type')
    op.drop_column('session', 'email_thread_id')
    op.drop_column('agent_share', 'source')
    # ### end Alembic commands ###
