"""add last_activity_at to agent_environment

Revision ID: 813b0bf363af
Revises: bb6811059aba
Create Date: 2026-01-08 18:15:29.982314

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '813b0bf363af'
down_revision = 'bb6811059aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_environment', sa.Column('last_activity_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_environment', 'last_activity_at')
    # ### end Alembic commands ###
