"""

Revision ID: 874dc8aa7c01
Revises: a1b2c3d4e5f6
Create Date: 2026-01-12 08:36:41.256973

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '874dc8aa7c01'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_plugin_link', sa.Column('disabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_plugin_link', 'disabled')
    # ### end Alembic commands ###
