"""change credential workspace fk to set null

Revision ID: 8b77ba42b38d
Revises: v2q3r4s5t6u7
Create Date: 2026-01-28 13:14:44.158294

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8b77ba42b38d'
down_revision = 'v2q3r4s5t6u7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('credential_user_workspace_id_fkey'), 'credential', type_='foreignkey')
    op.create_foreign_key(None, 'credential', 'user_workspace', ['user_workspace_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'credential', type_='foreignkey')
    op.create_foreign_key(op.f('credential_user_workspace_id_fkey'), 'credential', 'user_workspace', ['user_workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
