"""Add agent-credential many-to-many relationship

Revision ID: 8deb1f26c518
Revises: dff3725fe567
Create Date: 2025-12-22 16:06:15.851786

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8deb1f26c518'
down_revision = 'dff3725fe567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_credential_link',
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('credential_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['credential_id'], ['credential.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'credential_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_credential_link')
    # ### end Alembic commands ###
