"""add llm plugin marketplace tables

Revision ID: a1b2c3d4e5f6
Revises: 0df6011bb22d
Create Date: 2026-01-11 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '0df6011bb22d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create llm_plugin_marketplace table
    op.create_table('llm_plugin_marketplace',
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('owner_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('owner_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('git_branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('ssh_key_id', sa.Uuid(), nullable=True),
        sa.Column('public_discovery', sa.Boolean(), nullable=False),
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('status_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('last_sync_at', sa.DateTime(), nullable=True),
        sa.Column('sync_commit_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['ssh_key_id'], ['user_ssh_keys.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_plugin_marketplace_name'), 'llm_plugin_marketplace', ['name'], unique=False)
    op.create_index(op.f('ix_llm_plugin_marketplace_user_id'), 'llm_plugin_marketplace', ['user_id'], unique=False)
    op.create_index('idx_marketplace_name_unique', 'llm_plugin_marketplace', ['name'], unique=True)
    op.create_index('idx_marketplace_user', 'llm_plugin_marketplace', ['user_id'], unique=False)
    op.create_index('idx_marketplace_public', 'llm_plugin_marketplace', ['public_discovery'], unique=False)

    # Create llm_plugin_marketplace_plugin table
    op.create_table('llm_plugin_marketplace_plugin',
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('author_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('author_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('homepage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('source_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''),
        sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='local'),
        sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('source_branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='main'),
        sa.Column('source_commit_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('plugin_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('commit_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('marketplace_id', sa.Uuid(), nullable=False),
        sa.Column('config', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['marketplace_id'], ['llm_plugin_marketplace.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_plugin_marketplace_plugin_name'), 'llm_plugin_marketplace_plugin', ['name'], unique=False)
    op.create_index(op.f('ix_llm_plugin_marketplace_plugin_marketplace_id'), 'llm_plugin_marketplace_plugin', ['marketplace_id'], unique=False)
    op.create_index('idx_plugin_marketplace_name_unique', 'llm_plugin_marketplace_plugin', ['marketplace_id', 'name'], unique=True)
    op.create_index('idx_plugin_marketplace', 'llm_plugin_marketplace_plugin', ['marketplace_id'], unique=False)
    op.create_index('idx_plugin_category', 'llm_plugin_marketplace_plugin', ['category'], unique=False)

    # Create agent_plugin_link table
    op.create_table('agent_plugin_link',
        sa.Column('conversation_mode', sa.Boolean(), nullable=False),
        sa.Column('building_mode', sa.Boolean(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('agent_id', sa.Uuid(), nullable=False),
        sa.Column('plugin_id', sa.Uuid(), nullable=False),
        sa.Column('installed_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('installed_commit_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['plugin_id'], ['llm_plugin_marketplace_plugin.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_plugin_link_agent_id'), 'agent_plugin_link', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_plugin_link_plugin_id'), 'agent_plugin_link', ['plugin_id'], unique=False)
    op.create_index('idx_agent_plugin_unique', 'agent_plugin_link', ['agent_id', 'plugin_id'], unique=True)
    op.create_index('idx_agent_plugin_agent', 'agent_plugin_link', ['agent_id'], unique=False)
    op.create_index('idx_agent_plugin_plugin', 'agent_plugin_link', ['plugin_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop agent_plugin_link table
    op.drop_index('idx_agent_plugin_plugin', table_name='agent_plugin_link')
    op.drop_index('idx_agent_plugin_agent', table_name='agent_plugin_link')
    op.drop_index('idx_agent_plugin_unique', table_name='agent_plugin_link')
    op.drop_index(op.f('ix_agent_plugin_link_plugin_id'), table_name='agent_plugin_link')
    op.drop_index(op.f('ix_agent_plugin_link_agent_id'), table_name='agent_plugin_link')
    op.drop_table('agent_plugin_link')

    # Drop llm_plugin_marketplace_plugin table
    op.drop_index('idx_plugin_category', table_name='llm_plugin_marketplace_plugin')
    op.drop_index('idx_plugin_marketplace', table_name='llm_plugin_marketplace_plugin')
    op.drop_index('idx_plugin_marketplace_name_unique', table_name='llm_plugin_marketplace_plugin')
    op.drop_index(op.f('ix_llm_plugin_marketplace_plugin_marketplace_id'), table_name='llm_plugin_marketplace_plugin')
    op.drop_index(op.f('ix_llm_plugin_marketplace_plugin_name'), table_name='llm_plugin_marketplace_plugin')
    op.drop_table('llm_plugin_marketplace_plugin')

    # Drop llm_plugin_marketplace table
    op.drop_index('idx_marketplace_public', table_name='llm_plugin_marketplace')
    op.drop_index('idx_marketplace_user', table_name='llm_plugin_marketplace')
    op.drop_index('idx_marketplace_name_unique', table_name='llm_plugin_marketplace')
    op.drop_index(op.f('ix_llm_plugin_marketplace_user_id'), table_name='llm_plugin_marketplace')
    op.drop_index(op.f('ix_llm_plugin_marketplace_name'), table_name='llm_plugin_marketplace')
    op.drop_table('llm_plugin_marketplace')

    # ### end Alembic commands ###
