"""add interaction_status to session

Revision ID: a509ae4fadd1
Revises: 580bc34f4161
Create Date: 2025-12-29 23:32:53.329010

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a509ae4fadd1'
down_revision = '580bc34f4161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('session', sa.Column('interaction_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE session SET interaction_status = '' WHERE interaction_status IS NULL")
    # Make column NOT NULL
    op.alter_column('session', 'interaction_status', nullable=False, server_default='')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'interaction_status')
    # ### end Alembic commands ###
