"""add auth_token_hash to agent_environment

Revision ID: a6f8dccba412
Revises: 25a74abc7f4a
Create Date: 2026-06-21 07:06:45.005232

Adds the SHA-256 verification/revocation anchor for the scoped agent-environment
token. Left NULL for existing rows — the grace-window fallback in
``AgentEnvContextDep`` compares against ``config["auth_token"]`` verbatim until
the env is rotated (on next configure / bulk rebuild), which sets the hash.

NOTE: the autogenerated diff also picked up unrelated ``cli_device_login_request``
timezone-type drift (a pre-existing model/DB mismatch from another migration);
that drift was intentionally trimmed so this migration only touches the column +
index it is named for.
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = 'a6f8dccba412'
down_revision = '25a74abc7f4a'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        'agent_environment',
        sa.Column('auth_token_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    )
    op.create_index(
        op.f('ix_agent_environment_auth_token_hash'),
        'agent_environment',
        ['auth_token_hash'],
        unique=False,
    )


def downgrade():
    op.drop_index(op.f('ix_agent_environment_auth_token_hash'), table_name='agent_environment')
    op.drop_column('agent_environment', 'auth_token_hash')
