"""add agent handover config table

Revision ID: b26f2c36507c
Revises: 7ef8eae8f523
Create Date: 2026-01-01 16:09:05.749102

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b26f2c36507c'
down_revision = '7ef8eae8f523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_handover_config',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_agent_id', sa.Uuid(), nullable=False),
    sa.Column('target_agent_id', sa.Uuid(), nullable=False),
    sa.Column('handover_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_handover_config')
    # ### end Alembic commands ###
