"""Add pending messages tracking to Session model

Revision ID: b3ea462fe787
Revises: 813b0bf363af
Create Date: 2026-01-09 10:58:18.012227

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b3ea462fe787'
down_revision = '813b0bf363af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('pending_messages_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('session', sa.Column('cancel_pending_messages', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'cancel_pending_messages')
    op.drop_column('session', 'pending_messages_count')
    # ### end Alembic commands ###
