"""add_skill_package_tables

Creates the two tables behind the server skills catalog:

* ``skill_package`` — publisher-owned identity (reverse-DNS ``package_id``
  unique on the instance, name unique per publisher, visibility, listed flag).
* ``skill_package_revision`` — append-only content snapshots, unique on
  ``(package_id, revision_number)``.

The ``skill_package.latest_revision_id`` foreign key is added **after** both
tables exist: the two reference each other, so it cannot be inline on the
``CREATE TABLE`` (the revision table does not exist yet at that point).

``skill_package_revision`` carries two digests on purpose: ``content_hash``
over the snapshot tree (identity of the content) and ``archive_sha256`` over
the gzipped tarball the container downloads. The second is stored rather than
computed on demand because the plugin manifest carries it and that manifest is
built on the asyncio event loop.

Hand-edits to the autogenerated output:
  * the inline ``latest_revision_id`` FK was moved out into its own
    ``create_foreign_key`` after the second table (see above);
  * the ``agent_plugin_link.skill_package_revision_id`` column autogenerate
    folded in here was moved to its own migration
    (``add_agent_plugin_link_catalog_source``), so the tables and the link
    change stay separately reversible;
  * the ``cli_device_login_request`` timezone alterations were removed —
    pre-existing model/DB drift, unrelated to this change (same removal as
    revision ``2affe6c57bf7``).

Timestamps are naive ``DateTime`` to match the sibling
``agent_bundle`` / ``agent_bundle_revision`` tables; the plan's TIMESTAMPTZ
would have made this the only catalog table with a different convention.

Revision ID: c24bd7ff8728
Revises: 2affe6c57bf7
Create Date: 2026-09-08 14:28:26.603076

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = 'c24bd7ff8728'
down_revision = '2affe6c57bf7'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'skill_package',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('package_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('publisher_user_id', sa.Uuid(), nullable=True),
        sa.Column('source_agent_id', sa.Uuid(), nullable=True),
        sa.Column('latest_revision_id', sa.Uuid(), nullable=True),
        sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column('is_listed', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['publisher_user_id'], ['user.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['source_agent_id'], ['agent.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('package_id', name='uq_skill_package_package_id'),
        sa.UniqueConstraint('publisher_user_id', 'name', name='uq_skill_package_publisher_name'),
    )
    op.create_index('ix_skill_package_publisher', 'skill_package', ['publisher_user_id'], unique=False)
    op.create_index('ix_skill_package_visibility', 'skill_package', ['visibility'], unique=False)

    op.create_table(
        'skill_package_revision',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('package_id', sa.Uuid(), nullable=False),
        sa.Column('revision_number', sa.Integer(), nullable=False),
        sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column('frontmatter', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False),
        sa.Column('snapshot_path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
        sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column('archive_sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column('size_bytes', sa.Integer(), nullable=False),
        sa.Column('release_notes', sa.Text(), nullable=True),
        sa.Column('published_by_user_id', sa.Uuid(), nullable=True),
        sa.Column('published_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['package_id'], ['skill_package.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['published_by_user_id'], ['user.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('package_id', 'revision_number', name='uq_skill_package_revision_number'),
    )
    op.create_index(
        'ix_skill_package_revision_package',
        'skill_package_revision',
        ['package_id'],
        unique=False,
    )

    # Circular reference, so it lands last. SET NULL rather than CASCADE:
    # losing the pointer must not delete the package.
    op.create_foreign_key(
        'fk_skill_package_latest_revision',
        'skill_package',
        'skill_package_revision',
        ['latest_revision_id'],
        ['id'],
        ondelete='SET NULL',
    )


def downgrade():
    op.drop_constraint(
        'fk_skill_package_latest_revision', 'skill_package', type_='foreignkey'
    )
    op.drop_index('ix_skill_package_revision_package', table_name='skill_package_revision')
    op.drop_table('skill_package_revision')
    op.drop_index('ix_skill_package_visibility', table_name='skill_package')
    op.drop_index('ix_skill_package_publisher', table_name='skill_package')
    op.drop_table('skill_package')
