"""add cli device login request

Revision ID: c70a14722869
Revises: 3974f541ab0b
Create Date: 2026-06-20 17:38:59.665559

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c70a14722869'
down_revision = '3974f541ab0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cli_device_login_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_code_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('user_code', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('machine_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('machine_info', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('minted_token_id', sa.Uuid(), nullable=True),
    sa.Column('account_token_jwt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('client_ip', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['minted_token_id'], ['cli_token.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cli_device_login_request_device_code_hash'), 'cli_device_login_request', ['device_code_hash'], unique=True)
    op.create_index(op.f('ix_cli_device_login_request_status'), 'cli_device_login_request', ['status'], unique=False)
    op.create_index(op.f('ix_cli_device_login_request_user_code'), 'cli_device_login_request', ['user_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cli_device_login_request_user_code'), table_name='cli_device_login_request')
    op.drop_index(op.f('ix_cli_device_login_request_status'), table_name='cli_device_login_request')
    op.drop_index(op.f('ix_cli_device_login_request_device_code_hash'), table_name='cli_device_login_request')
    op.drop_table('cli_device_login_request')
    # ### end Alembic commands ###
