"""add agent_email_integration table

Revision ID: cc1e27a71798
Revises: 029b03776737
Create Date: 2026-02-12 14:02:26.791791

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cc1e27a71798'
down_revision = '029b03776737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_email_integration',
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('access_mode', sa.Enum('OPEN', 'RESTRICTED', name='emailaccessmode'), nullable=False),
    sa.Column('auto_approve_email_pattern', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('allowed_domains', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('max_clones', sa.Integer(), nullable=False),
    sa.Column('clone_share_mode', sa.Enum('USER', 'BUILDER', name='emailclonesharemode'), nullable=False),
    sa.Column('incoming_mailbox', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('outgoing_from_address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('incoming_server_id', sa.Uuid(), nullable=True),
    sa.Column('outgoing_server_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incoming_server_id'], ['mail_server_config.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outgoing_server_id'], ['mail_server_config.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', name='uq_agent_email_integration_agent_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_email_integration')
    # ### end Alembic commands ###
