"""add app sync tables

Revision ID: d54391bd8cf2
Revises: 6e43bbbec5cc
Create Date: 2026-05-31 07:16:47.058814

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd54391bd8cf2'
down_revision = '6e43bbbec5cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_sync_device',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_label', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('public_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_client_id', sa.Uuid(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_app_sync_device_user_id', 'app_sync_device', ['user_id'], unique=False)
    op.create_table('app_sync_pairing',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('pairing_code_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('new_device_pubkey', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device_label', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('sealed_umk', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_app_sync_pairing_code_hash', 'app_sync_pairing', ['pairing_code_hash'], unique=False)
    op.create_index('ix_app_sync_pairing_user_id', 'app_sync_pairing', ['user_id'], unique=False)
    op.create_table('app_sync_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('collection', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('client_entity_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('payload_ciphertext', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enc_umk_version', sa.Integer(), nullable=False),
    sa.Column('payload_bytes', sa.Integer(), nullable=False),
    sa.Column('content_fingerprint', sqlmodel.sql.sqltypes.AutoString(length=88), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('client_updated_at', sa.DateTime(), nullable=False),
    sa.Column('server_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_writer_client_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'collection', 'client_entity_id', name='ix_app_sync_record_natural')
    )
    op.create_index('ix_app_sync_record_user_collection', 'app_sync_record', ['user_id', 'collection'], unique=False)
    op.create_index('ix_app_sync_record_user_id', 'app_sync_record', ['user_id'], unique=False)
    op.create_index('ix_app_sync_record_user_seq', 'app_sync_record', ['user_id', 'seq'], unique=False)
    op.create_table('app_sync_state',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('current_seq', sa.BigInteger(), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('active_umk_version', sa.Integer(), nullable=False),
    sa.Column('e2e_initialized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('app_sync_key_envelope',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('wrap_method', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('umk_version', sa.Integer(), nullable=False),
    sa.Column('wrapped_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kdf', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('kdf_params', sa.JSON(), nullable=True),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['app_sync_device.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'wrap_method', 'umk_version', 'device_id', name='uq_app_sync_key_envelope_unlock')
    )
    op.create_index('ix_app_sync_key_envelope_user_id', 'app_sync_key_envelope', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_app_sync_key_envelope_user_id', table_name='app_sync_key_envelope')
    op.drop_table('app_sync_key_envelope')
    op.drop_table('app_sync_state')
    op.drop_index('ix_app_sync_record_user_seq', table_name='app_sync_record')
    op.drop_index('ix_app_sync_record_user_id', table_name='app_sync_record')
    op.drop_index('ix_app_sync_record_user_collection', table_name='app_sync_record')
    op.drop_table('app_sync_record')
    op.drop_index('ix_app_sync_pairing_user_id', table_name='app_sync_pairing')
    op.drop_index('ix_app_sync_pairing_code_hash', table_name='app_sync_pairing')
    op.drop_table('app_sync_pairing')
    op.drop_index('ix_app_sync_device_user_id', table_name='app_sync_device')
    op.drop_table('app_sync_device')
    # ### end Alembic commands ###
