"""add status and status_message fields to session_message

Revision ID: e346c86d4373
Revises: bfbae71690bb
Create Date: 2025-12-27 16:43:08.378969

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e346c86d4373'
down_revision = 'bfbae71690bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('message', sa.Column('status_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'status_message')
    op.drop_column('message', 'status')
    # ### end Alembic commands ###
