"""add membership row, provider admin credentials and minted provisioning

Revision ID: ed8d6a23f13c
Revises: adffe56ef505
Create Date: 2026-09-06 11:05:18.465016

Three changes, one of which carries all the risk.

1. ``provider_admin_credential`` — the instance-wide provider administration
   secret. ``created_by_id`` is **SET NULL**, never CASCADE: user deletion is a
   bare ``session.delete(user)`` relying entirely on database-level ``ON
   DELETE``, so a CASCADE here would let one ``DELETE /users/{id}`` destroy the
   only means of revoking every key the instance has ever minted.

2. ``managed_ai_credential`` gains ``provisioning_mode`` (server default
   ``'shared'`` — every pre-existing record is, by construction, a shared-key
   record) and ``provider_admin_credential_id``, and its ``encrypted_data``
   becomes nullable, because a minted parent holds no key of its own.

3. ``managed_ai_credential_membership`` — **and its backfill, which is the risky
   step.** Membership was previously *derived*: a user was a member of a parent
   iff an ``ai_credential`` row existed whose ``managed_credential_id`` pointed
   at it. This migration turns that derivation into rows, once, and after it the
   derivation is gone. A backfill that quietly drops a member produces an install
   where somebody's credential is invisible to the admin UI and to every later
   reconcile — a failure nobody notices until that person has no key.

   **What the backfill assumes about the rows it reads, stated so it can be
   checked rather than trusted:**

   a. *Every parent at this revision is shared-mode.* True by construction:
      ``provisioning_mode`` is created in this same migration and no code path
      existed to write ``'minted'`` before it. Hence every backfilled row is
      ``status='not_applicable'`` with no ``external_key_ref``.
   b. *A membership is exactly ``(managed_credential_id, owner_id)``.* If two
      children of one parent share an owner, the derivation is ambiguous and
      there is no correct winner to pick. The unique constraint would reject it;
      the explicit pre-check below rejects it first, with a message that names
      the pairs. **Loud failure, never a skipped row.**
   c. *A child whose ``managed_credential_id`` is NULL is a member of nothing.*
      That is a classification, not an omission: the FK is ``ON DELETE SET
      NULL`` and ``AICredential.managed_credential_id`` documents such rows as
      orphans that degrade to plain ``is_admin_managed`` credentials. They are
      excluded deliberately.

   A post-check asserts the inserted count equals the eligible-children count, so
   a partial insert fails the migration instead of shipping a short member list.

The three ``cli_device_login_request`` timestamp alterations that autogenerate
re-proposes on every run were removed: the model is wrong there, the database is
right, and applying them would degrade three timezone-aware columns.
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed8d6a23f13c'
down_revision = 'adffe56ef505'
branch_labels = None
depends_on = None


# The FK this migration adds to ``managed_ai_credential`` pointing at the new
# ``provider_admin_credential`` table. Named so the downgrade can drop it by
# name rather than by autogenerated guess.
PROVIDER_ADMIN_FK = "fk_managed_ai_credential_provider_admin_credential"


def _backfill_memberships() -> None:
    """Materialise one membership row per existing admin-managed child."""
    conn = op.get_bind()

    duplicates = conn.execute(
        sa.text(
            """
            SELECT managed_credential_id, owner_id, COUNT(*) AS n
            FROM ai_credential
            WHERE managed_credential_id IS NOT NULL
            GROUP BY managed_credential_id, owner_id
            HAVING COUNT(*) > 1
            """
        )
    ).fetchall()
    if duplicates:
        # Assumption (b) violated. Refuse rather than choose: picking either row
        # would write a member list that is silently wrong for that user.
        detail = ", ".join(
            f"parent={row[0]} owner={row[1]} children={row[2]}"
            for row in duplicates
        )
        raise RuntimeError(
            "Cannot backfill managed_ai_credential_membership: more than one "
            "child credential exists for the same (parent, owner) pair, so "
            "membership cannot be derived unambiguously. Resolve these first: "
            f"{detail}"
        )

    expected = conn.execute(
        sa.text(
            "SELECT COUNT(*) FROM ai_credential "
            "WHERE managed_credential_id IS NOT NULL"
        )
    ).scalar_one()

    # ``gen_random_uuid()`` is built into PostgreSQL 13+ (no pgcrypto extension
    # needed) and this stack runs 17. It is the first use of it in this tree,
    # hence the note.
    result = conn.execute(
        sa.text(
            """
            INSERT INTO managed_ai_credential_membership (
                id, managed_credential_id, user_id, status, ai_credential_id,
                external_key_ref, provision_attempts, next_attempt_at,
                last_error, created_at, updated_at
            )
            SELECT
                gen_random_uuid(),
                c.managed_credential_id,
                c.owner_id,
                'not_applicable',
                c.id,
                NULL,
                0,
                NULL,
                NULL,
                COALESCE(c.created_at, NOW()),
                NOW()
            FROM ai_credential c
            WHERE c.managed_credential_id IS NOT NULL
            """
        )
    )

    # The rows **this statement** inserted, not the table's total. They are the
    # same number today because the table is created in this same migration, and
    # that is exactly why the weaker check would be easy to keep by accident: it
    # would go on passing while measuring the wrong thing the moment this file is
    # adapted or re-run against a populated table.
    inserted = result.rowcount
    if inserted != expected:
        raise RuntimeError(
            "managed_ai_credential_membership backfill is incomplete: "
            f"{expected} admin-managed child credential(s) but {inserted} "
            "membership row(s). Refusing to leave members unrepresented."
        )


def upgrade():
    op.create_table('provider_admin_credential',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('encrypted_secret', sa.Text(), nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verify_error', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_admin_credential_type', 'provider_admin_credential', ['provider_type'], unique=False)
    op.create_table('managed_ai_credential_membership',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('managed_credential_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('ai_credential_id', sa.Uuid(), nullable=True),
    sa.Column('external_key_ref', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('provision_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ai_credential_id'], ['ai_credential.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['managed_credential_id'], ['managed_ai_credential.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('managed_credential_id', 'user_id', name='uq_managed_ai_credential_membership_parent_user')
    )
    op.create_index('ix_managed_ai_cred_membership_status_next', 'managed_ai_credential_membership', ['status', 'next_attempt_at'], unique=False)
    op.create_index('ix_managed_ai_cred_membership_user', 'managed_ai_credential_membership', ['user_id'], unique=False)
    op.create_index(op.f('ix_managed_ai_credential_membership_managed_credential_id'), 'managed_ai_credential_membership', ['managed_credential_id'], unique=False)
    op.add_column('managed_ai_credential', sa.Column('provisioning_mode', sa.String(length=24), server_default='shared', nullable=False))
    op.add_column('managed_ai_credential', sa.Column('provider_admin_credential_id', sa.Uuid(), nullable=True))
    op.alter_column('managed_ai_credential', 'encrypted_data',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_foreign_key(PROVIDER_ADMIN_FK, 'managed_ai_credential', 'provider_admin_credential', ['provider_admin_credential_id'], ['id'], ondelete='SET NULL')

    # Last, so it runs against the finished schema.
    _backfill_memberships()


def downgrade():
    conn = op.get_bind()

    # Precondition, enforced rather than documented: restoring NOT NULL on
    # ``encrypted_data`` is impossible while a minted parent exists, because a
    # minted parent legitimately has no key. Deleting them here would destroy
    # records (and orphan live provider keys, which only this schema knows how
    # to revoke), so the downgrade refuses and says what to remove first.
    minted = conn.execute(
        sa.text(
            "SELECT COUNT(*) FROM managed_ai_credential "
            "WHERE provisioning_mode = 'minted'"
        )
    ).scalar_one()
    if minted:
        raise RuntimeError(
            f"Cannot downgrade: {minted} managed AI credential record(s) are in "
            "minted mode and hold no key of their own. Delete them through the "
            "admin API first — that path revokes their members' provider keys; "
            "dropping the schema here would leave those keys live and "
            "unrevocable."
        )

    # Past this point no minted parent exists, so no ``external_key_ref`` can
    # survive and no provider key is stranded by the drop. What IS lost is the
    # durable record of every membership that ever failed or was suspended —
    # dropping the table takes those with it, silently. Stated here because a
    # downgrade that destroys an audit trail should say so.


    op.drop_constraint(PROVIDER_ADMIN_FK, 'managed_ai_credential', type_='foreignkey')
    op.alter_column('managed_ai_credential', 'encrypted_data',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('managed_ai_credential', 'provider_admin_credential_id')
    op.drop_column('managed_ai_credential', 'provisioning_mode')
    op.drop_index(op.f('ix_managed_ai_credential_membership_managed_credential_id'), table_name='managed_ai_credential_membership')
    op.drop_index('ix_managed_ai_cred_membership_user', table_name='managed_ai_credential_membership')
    op.drop_index('ix_managed_ai_cred_membership_status_next', table_name='managed_ai_credential_membership')
    op.drop_table('managed_ai_credential_membership')
    op.drop_index('ix_provider_admin_credential_type', table_name='provider_admin_credential')
    op.drop_table('provider_admin_credential')
