"""fix_fields_for_canceled_messages

Revision ID: fa1b0655c531
Revises: b3ea462fe787
Create Date: 2026-01-09 11:27:42.941537

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fa1b0655c531'
down_revision = 'b3ea462fe787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('sent_to_agent_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='pending'))
    op.drop_column('session', 'cancel_pending_messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('cancel_pending_messages', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('message', 'sent_to_agent_status')
    # ### end Alembic commands ###
