/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as WebappWebappTokenRouteImport } from './routes/webapp/$webappToken'
import { Route as OauthMcpConsentRouteImport } from './routes/oauth/mcp-consent'
import { Route as LoginMfaRouteImport } from './routes/login/mfa'
import { Route as GuestFileViewerRouteImport } from './routes/guest/file-viewer'
import { Route as GuestGuestShareTokenRouteImport } from './routes/guest/$guestShareToken'
import { Route as DesktopAuthConsentRouteImport } from './routes/desktop-auth/consent'
import { Route as DashboardFullscreenDashboardIdRouteImport } from './routes/dashboard-fullscreen/$dashboardId'
import { Route as AppAuthConsentRouteImport } from './routes/app-auth/consent'
import { Route as AgentApiSpecAgentIdRouteImport } from './routes/agent-api-spec/$agentId'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSessionsRouteImport } from './routes/_layout/sessions'
import { Route as LayoutKnowledgeSourcesRouteImport } from './routes/_layout/knowledge-sources'
import { Route as LayoutCredentialsRouteImport } from './routes/_layout/credentials'
import { Route as LayoutCatalogRouteImport } from './routes/_layout/catalog'
import { Route as LayoutAgentsRouteImport } from './routes/_layout/agents'
import { Route as LayoutActivitiesAllRouteImport } from './routes/_layout/activities-all'
import { Route as LayoutActivitiesRouteImport } from './routes/_layout/activities'
import { Route as LayoutTasksIndexRouteImport } from './routes/_layout/tasks/index'
import { Route as LayoutSessionsIndexRouteImport } from './routes/_layout/sessions/index'
import { Route as LayoutDashboardsIndexRouteImport } from './routes/_layout/dashboards/index'
import { Route as LayoutCatalogIndexRouteImport } from './routes/_layout/catalog/index'
import { Route as LayoutAgenticTeamsIndexRouteImport } from './routes/_layout/agentic-teams/index'
import { Route as McpProvidersOauthCallbackRouteImport } from './routes/mcp-providers/oauth/callback'
import { Route as CredentialsOauthCallbackRouteImport } from './routes/credentials/oauth/callback'
import { Route as LayoutTasksShortCodeRouteImport } from './routes/_layout/tasks/$shortCode'
import { Route as LayoutTaskTaskIdRouteImport } from './routes/_layout/task/$taskId'
import { Route as LayoutSessionSessionIdRouteImport } from './routes/_layout/session/$sessionId'
import { Route as LayoutKnowledgeSourceSourceIdRouteImport } from './routes/_layout/knowledge-source/$sourceId'
import { Route as LayoutDashboardsDashboardIdRouteImport } from './routes/_layout/dashboards/$dashboardId'
import { Route as LayoutCredentialCredentialIdRouteImport } from './routes/_layout/credential/$credentialId'
import { Route as LayoutCatalogAgentsRouteImport } from './routes/_layout/catalog/agents'
import { Route as LayoutAgenticTeamsTeamIdRouteImport } from './routes/_layout/agentic-teams/$teamId'
import { Route as LayoutAgentCreatingRouteImport } from './routes/_layout/agent/creating'
import { Route as LayoutAgentAgentIdRouteImport } from './routes/_layout/agent/$agentId'
import { Route as LayoutAdminUsersRouteImport } from './routes/_layout/admin/users'
import { Route as LayoutAdminMarketplacesRouteImport } from './routes/_layout/admin/marketplaces'
import { Route as LayoutAdminLlmProvidersRouteImport } from './routes/_layout/admin/llm-providers'
import { Route as LayoutAdminAgentEnvsRouteImport } from './routes/_layout/admin/agent-envs'
import { Route as LayoutSessionsAgentAgentIdRouteImport } from './routes/_layout/sessions/agent/$agentId'
import { Route as LayoutEnvironmentEnvIdFileRouteImport } from './routes/_layout/environment/$envId/file'
import { Route as LayoutEnvironmentEnvIdDatabaseRouteImport } from './routes/_layout/environment/$envId/database'
import { Route as LayoutCatalogAgentsInstallRouteImport } from './routes/_layout/catalog/agents/install'
import { Route as LayoutAgentAgentIdConversationsRouteImport } from './routes/_layout/agent/$agentId/conversations'
import { Route as LayoutAdminMarketplaceMarketplaceIdRouteImport } from './routes/_layout/admin/marketplace/$marketplaceId'
import { Route as LayoutCatalogAgentsInstallBundleIdRouteImport } from './routes/_layout/catalog/agents/install/$bundleId'
import { Route as LayoutAdminMarketplacePluginPluginIdRouteImport } from './routes/_layout/admin/marketplace/plugin/$pluginId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const WebappWebappTokenRoute = WebappWebappTokenRouteImport.update({
  id: '/webapp/$webappToken',
  path: '/webapp/$webappToken',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthMcpConsentRoute = OauthMcpConsentRouteImport.update({
  id: '/oauth/mcp-consent',
  path: '/oauth/mcp-consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginMfaRoute = LoginMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => LoginRoute,
} as any)
const GuestFileViewerRoute = GuestFileViewerRouteImport.update({
  id: '/guest/file-viewer',
  path: '/guest/file-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestGuestShareTokenRoute = GuestGuestShareTokenRouteImport.update({
  id: '/guest/$guestShareToken',
  path: '/guest/$guestShareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopAuthConsentRoute = DesktopAuthConsentRouteImport.update({
  id: '/desktop-auth/consent',
  path: '/desktop-auth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFullscreenDashboardIdRoute =
  DashboardFullscreenDashboardIdRouteImport.update({
    id: '/dashboard-fullscreen/$dashboardId',
    path: '/dashboard-fullscreen/$dashboardId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAuthConsentRoute = AppAuthConsentRouteImport.update({
  id: '/app-auth/consent',
  path: '/app-auth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentApiSpecAgentIdRoute = AgentApiSpecAgentIdRouteImport.update({
  id: '/agent-api-spec/$agentId',
  path: '/agent-api-spec/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSessionsRoute = LayoutSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKnowledgeSourcesRoute = LayoutKnowledgeSourcesRouteImport.update({
  id: '/knowledge-sources',
  path: '/knowledge-sources',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCredentialsRoute = LayoutCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCatalogRoute = LayoutCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgentsRoute = LayoutAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutActivitiesAllRoute = LayoutActivitiesAllRouteImport.update({
  id: '/activities-all',
  path: '/activities-all',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutActivitiesRoute = LayoutActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTasksIndexRoute = LayoutTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSessionsIndexRoute = LayoutSessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutSessionsRoute,
} as any)
const LayoutDashboardsIndexRoute = LayoutDashboardsIndexRouteImport.update({
  id: '/dashboards/',
  path: '/dashboards/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCatalogIndexRoute = LayoutCatalogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutCatalogRoute,
} as any)
const LayoutAgenticTeamsIndexRoute = LayoutAgenticTeamsIndexRouteImport.update({
  id: '/agentic-teams/',
  path: '/agentic-teams/',
  getParentRoute: () => LayoutRoute,
} as any)
const McpProvidersOauthCallbackRoute =
  McpProvidersOauthCallbackRouteImport.update({
    id: '/mcp-providers/oauth/callback',
    path: '/mcp-providers/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const CredentialsOauthCallbackRoute =
  CredentialsOauthCallbackRouteImport.update({
    id: '/credentials/oauth/callback',
    path: '/credentials/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const LayoutTasksShortCodeRoute = LayoutTasksShortCodeRouteImport.update({
  id: '/tasks/$shortCode',
  path: '/tasks/$shortCode',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTaskTaskIdRoute = LayoutTaskTaskIdRouteImport.update({
  id: '/task/$taskId',
  path: '/task/$taskId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSessionSessionIdRoute = LayoutSessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKnowledgeSourceSourceIdRoute =
  LayoutKnowledgeSourceSourceIdRouteImport.update({
    id: '/knowledge-source/$sourceId',
    path: '/knowledge-source/$sourceId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutDashboardsDashboardIdRoute =
  LayoutDashboardsDashboardIdRouteImport.update({
    id: '/dashboards/$dashboardId',
    path: '/dashboards/$dashboardId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutCredentialCredentialIdRoute =
  LayoutCredentialCredentialIdRouteImport.update({
    id: '/credential/$credentialId',
    path: '/credential/$credentialId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutCatalogAgentsRoute = LayoutCatalogAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => LayoutCatalogRoute,
} as any)
const LayoutAgenticTeamsTeamIdRoute =
  LayoutAgenticTeamsTeamIdRouteImport.update({
    id: '/agentic-teams/$teamId',
    path: '/agentic-teams/$teamId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAgentCreatingRoute = LayoutAgentCreatingRouteImport.update({
  id: '/agent/creating',
  path: '/agent/creating',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgentAgentIdRoute = LayoutAgentAgentIdRouteImport.update({
  id: '/agent/$agentId',
  path: '/agent/$agentId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminUsersRoute = LayoutAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminMarketplacesRoute = LayoutAdminMarketplacesRouteImport.update({
  id: '/admin/marketplaces',
  path: '/admin/marketplaces',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminLlmProvidersRoute = LayoutAdminLlmProvidersRouteImport.update({
  id: '/admin/llm-providers',
  path: '/admin/llm-providers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminAgentEnvsRoute = LayoutAdminAgentEnvsRouteImport.update({
  id: '/admin/agent-envs',
  path: '/admin/agent-envs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSessionsAgentAgentIdRoute =
  LayoutSessionsAgentAgentIdRouteImport.update({
    id: '/agent/$agentId',
    path: '/agent/$agentId',
    getParentRoute: () => LayoutSessionsRoute,
  } as any)
const LayoutEnvironmentEnvIdFileRoute =
  LayoutEnvironmentEnvIdFileRouteImport.update({
    id: '/environment/$envId/file',
    path: '/environment/$envId/file',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutEnvironmentEnvIdDatabaseRoute =
  LayoutEnvironmentEnvIdDatabaseRouteImport.update({
    id: '/environment/$envId/database',
    path: '/environment/$envId/database',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutCatalogAgentsInstallRoute =
  LayoutCatalogAgentsInstallRouteImport.update({
    id: '/install',
    path: '/install',
    getParentRoute: () => LayoutCatalogAgentsRoute,
  } as any)
const LayoutAgentAgentIdConversationsRoute =
  LayoutAgentAgentIdConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => LayoutAgentAgentIdRoute,
  } as any)
const LayoutAdminMarketplaceMarketplaceIdRoute =
  LayoutAdminMarketplaceMarketplaceIdRouteImport.update({
    id: '/admin/marketplace/$marketplaceId',
    path: '/admin/marketplace/$marketplaceId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutCatalogAgentsInstallBundleIdRoute =
  LayoutCatalogAgentsInstallBundleIdRouteImport.update({
    id: '/$bundleId',
    path: '/$bundleId',
    getParentRoute: () => LayoutCatalogAgentsInstallRoute,
  } as any)
const LayoutAdminMarketplacePluginPluginIdRoute =
  LayoutAdminMarketplacePluginPluginIdRouteImport.update({
    id: '/admin/marketplace/plugin/$pluginId',
    path: '/admin/marketplace/plugin/$pluginId',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRouteWithChildren
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/activities': typeof LayoutActivitiesRoute
  '/activities-all': typeof LayoutActivitiesAllRoute
  '/agents': typeof LayoutAgentsRoute
  '/catalog': typeof LayoutCatalogRouteWithChildren
  '/credentials': typeof LayoutCredentialsRoute
  '/knowledge-sources': typeof LayoutKnowledgeSourcesRoute
  '/sessions': typeof LayoutSessionsRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/agent-api-spec/$agentId': typeof AgentApiSpecAgentIdRoute
  '/app-auth/consent': typeof AppAuthConsentRoute
  '/dashboard-fullscreen/$dashboardId': typeof DashboardFullscreenDashboardIdRoute
  '/desktop-auth/consent': typeof DesktopAuthConsentRoute
  '/guest/$guestShareToken': typeof GuestGuestShareTokenRoute
  '/guest/file-viewer': typeof GuestFileViewerRoute
  '/login/mfa': typeof LoginMfaRoute
  '/oauth/mcp-consent': typeof OauthMcpConsentRoute
  '/webapp/$webappToken': typeof WebappWebappTokenRoute
  '/': typeof LayoutIndexRoute
  '/login/': typeof LoginIndexRoute
  '/admin/agent-envs': typeof LayoutAdminAgentEnvsRoute
  '/admin/llm-providers': typeof LayoutAdminLlmProvidersRoute
  '/admin/marketplaces': typeof LayoutAdminMarketplacesRoute
  '/admin/users': typeof LayoutAdminUsersRoute
  '/agent/$agentId': typeof LayoutAgentAgentIdRouteWithChildren
  '/agent/creating': typeof LayoutAgentCreatingRoute
  '/agentic-teams/$teamId': typeof LayoutAgenticTeamsTeamIdRoute
  '/catalog/agents': typeof LayoutCatalogAgentsRouteWithChildren
  '/credential/$credentialId': typeof LayoutCredentialCredentialIdRoute
  '/dashboards/$dashboardId': typeof LayoutDashboardsDashboardIdRoute
  '/knowledge-source/$sourceId': typeof LayoutKnowledgeSourceSourceIdRoute
  '/session/$sessionId': typeof LayoutSessionSessionIdRoute
  '/task/$taskId': typeof LayoutTaskTaskIdRoute
  '/tasks/$shortCode': typeof LayoutTasksShortCodeRoute
  '/credentials/oauth/callback': typeof CredentialsOauthCallbackRoute
  '/mcp-providers/oauth/callback': typeof McpProvidersOauthCallbackRoute
  '/agentic-teams': typeof LayoutAgenticTeamsIndexRoute
  '/catalog/': typeof LayoutCatalogIndexRoute
  '/dashboards': typeof LayoutDashboardsIndexRoute
  '/sessions/': typeof LayoutSessionsIndexRoute
  '/tasks': typeof LayoutTasksIndexRoute
  '/admin/marketplace/$marketplaceId': typeof LayoutAdminMarketplaceMarketplaceIdRoute
  '/agent/$agentId/conversations': typeof LayoutAgentAgentIdConversationsRoute
  '/catalog/agents/install': typeof LayoutCatalogAgentsInstallRouteWithChildren
  '/environment/$envId/database': typeof LayoutEnvironmentEnvIdDatabaseRoute
  '/environment/$envId/file': typeof LayoutEnvironmentEnvIdFileRoute
  '/sessions/agent/$agentId': typeof LayoutSessionsAgentAgentIdRoute
  '/admin/marketplace/plugin/$pluginId': typeof LayoutAdminMarketplacePluginPluginIdRoute
  '/catalog/agents/install/$bundleId': typeof LayoutCatalogAgentsInstallBundleIdRoute
}
export interface FileRoutesByTo {
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/activities': typeof LayoutActivitiesRoute
  '/activities-all': typeof LayoutActivitiesAllRoute
  '/agents': typeof LayoutAgentsRoute
  '/credentials': typeof LayoutCredentialsRoute
  '/knowledge-sources': typeof LayoutKnowledgeSourcesRoute
  '/settings': typeof LayoutSettingsRoute
  '/agent-api-spec/$agentId': typeof AgentApiSpecAgentIdRoute
  '/app-auth/consent': typeof AppAuthConsentRoute
  '/dashboard-fullscreen/$dashboardId': typeof DashboardFullscreenDashboardIdRoute
  '/desktop-auth/consent': typeof DesktopAuthConsentRoute
  '/guest/$guestShareToken': typeof GuestGuestShareTokenRoute
  '/guest/file-viewer': typeof GuestFileViewerRoute
  '/login/mfa': typeof LoginMfaRoute
  '/oauth/mcp-consent': typeof OauthMcpConsentRoute
  '/webapp/$webappToken': typeof WebappWebappTokenRoute
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginIndexRoute
  '/admin/agent-envs': typeof LayoutAdminAgentEnvsRoute
  '/admin/llm-providers': typeof LayoutAdminLlmProvidersRoute
  '/admin/marketplaces': typeof LayoutAdminMarketplacesRoute
  '/admin/users': typeof LayoutAdminUsersRoute
  '/agent/$agentId': typeof LayoutAgentAgentIdRouteWithChildren
  '/agent/creating': typeof LayoutAgentCreatingRoute
  '/agentic-teams/$teamId': typeof LayoutAgenticTeamsTeamIdRoute
  '/catalog/agents': typeof LayoutCatalogAgentsRouteWithChildren
  '/credential/$credentialId': typeof LayoutCredentialCredentialIdRoute
  '/dashboards/$dashboardId': typeof LayoutDashboardsDashboardIdRoute
  '/knowledge-source/$sourceId': typeof LayoutKnowledgeSourceSourceIdRoute
  '/session/$sessionId': typeof LayoutSessionSessionIdRoute
  '/task/$taskId': typeof LayoutTaskTaskIdRoute
  '/tasks/$shortCode': typeof LayoutTasksShortCodeRoute
  '/credentials/oauth/callback': typeof CredentialsOauthCallbackRoute
  '/mcp-providers/oauth/callback': typeof McpProvidersOauthCallbackRoute
  '/agentic-teams': typeof LayoutAgenticTeamsIndexRoute
  '/catalog': typeof LayoutCatalogIndexRoute
  '/dashboards': typeof LayoutDashboardsIndexRoute
  '/sessions': typeof LayoutSessionsIndexRoute
  '/tasks': typeof LayoutTasksIndexRoute
  '/admin/marketplace/$marketplaceId': typeof LayoutAdminMarketplaceMarketplaceIdRoute
  '/agent/$agentId/conversations': typeof LayoutAgentAgentIdConversationsRoute
  '/catalog/agents/install': typeof LayoutCatalogAgentsInstallRouteWithChildren
  '/environment/$envId/database': typeof LayoutEnvironmentEnvIdDatabaseRoute
  '/environment/$envId/file': typeof LayoutEnvironmentEnvIdFileRoute
  '/sessions/agent/$agentId': typeof LayoutSessionsAgentAgentIdRoute
  '/admin/marketplace/plugin/$pluginId': typeof LayoutAdminMarketplacePluginPluginIdRoute
  '/catalog/agents/install/$bundleId': typeof LayoutCatalogAgentsInstallBundleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/activities': typeof LayoutActivitiesRoute
  '/_layout/activities-all': typeof LayoutActivitiesAllRoute
  '/_layout/agents': typeof LayoutAgentsRoute
  '/_layout/catalog': typeof LayoutCatalogRouteWithChildren
  '/_layout/credentials': typeof LayoutCredentialsRoute
  '/_layout/knowledge-sources': typeof LayoutKnowledgeSourcesRoute
  '/_layout/sessions': typeof LayoutSessionsRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/agent-api-spec/$agentId': typeof AgentApiSpecAgentIdRoute
  '/app-auth/consent': typeof AppAuthConsentRoute
  '/dashboard-fullscreen/$dashboardId': typeof DashboardFullscreenDashboardIdRoute
  '/desktop-auth/consent': typeof DesktopAuthConsentRoute
  '/guest/$guestShareToken': typeof GuestGuestShareTokenRoute
  '/guest/file-viewer': typeof GuestFileViewerRoute
  '/login/mfa': typeof LoginMfaRoute
  '/oauth/mcp-consent': typeof OauthMcpConsentRoute
  '/webapp/$webappToken': typeof WebappWebappTokenRoute
  '/_layout/': typeof LayoutIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_layout/admin/agent-envs': typeof LayoutAdminAgentEnvsRoute
  '/_layout/admin/llm-providers': typeof LayoutAdminLlmProvidersRoute
  '/_layout/admin/marketplaces': typeof LayoutAdminMarketplacesRoute
  '/_layout/admin/users': typeof LayoutAdminUsersRoute
  '/_layout/agent/$agentId': typeof LayoutAgentAgentIdRouteWithChildren
  '/_layout/agent/creating': typeof LayoutAgentCreatingRoute
  '/_layout/agentic-teams/$teamId': typeof LayoutAgenticTeamsTeamIdRoute
  '/_layout/catalog/agents': typeof LayoutCatalogAgentsRouteWithChildren
  '/_layout/credential/$credentialId': typeof LayoutCredentialCredentialIdRoute
  '/_layout/dashboards/$dashboardId': typeof LayoutDashboardsDashboardIdRoute
  '/_layout/knowledge-source/$sourceId': typeof LayoutKnowledgeSourceSourceIdRoute
  '/_layout/session/$sessionId': typeof LayoutSessionSessionIdRoute
  '/_layout/task/$taskId': typeof LayoutTaskTaskIdRoute
  '/_layout/tasks/$shortCode': typeof LayoutTasksShortCodeRoute
  '/credentials/oauth/callback': typeof CredentialsOauthCallbackRoute
  '/mcp-providers/oauth/callback': typeof McpProvidersOauthCallbackRoute
  '/_layout/agentic-teams/': typeof LayoutAgenticTeamsIndexRoute
  '/_layout/catalog/': typeof LayoutCatalogIndexRoute
  '/_layout/dashboards/': typeof LayoutDashboardsIndexRoute
  '/_layout/sessions/': typeof LayoutSessionsIndexRoute
  '/_layout/tasks/': typeof LayoutTasksIndexRoute
  '/_layout/admin/marketplace/$marketplaceId': typeof LayoutAdminMarketplaceMarketplaceIdRoute
  '/_layout/agent/$agentId/conversations': typeof LayoutAgentAgentIdConversationsRoute
  '/_layout/catalog/agents/install': typeof LayoutCatalogAgentsInstallRouteWithChildren
  '/_layout/environment/$envId/database': typeof LayoutEnvironmentEnvIdDatabaseRoute
  '/_layout/environment/$envId/file': typeof LayoutEnvironmentEnvIdFileRoute
  '/_layout/sessions/agent/$agentId': typeof LayoutSessionsAgentAgentIdRoute
  '/_layout/admin/marketplace/plugin/$pluginId': typeof LayoutAdminMarketplacePluginPluginIdRoute
  '/_layout/catalog/agents/install/$bundleId': typeof LayoutCatalogAgentsInstallBundleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/activities'
    | '/activities-all'
    | '/agents'
    | '/catalog'
    | '/credentials'
    | '/knowledge-sources'
    | '/sessions'
    | '/settings'
    | '/agent-api-spec/$agentId'
    | '/app-auth/consent'
    | '/dashboard-fullscreen/$dashboardId'
    | '/desktop-auth/consent'
    | '/guest/$guestShareToken'
    | '/guest/file-viewer'
    | '/login/mfa'
    | '/oauth/mcp-consent'
    | '/webapp/$webappToken'
    | '/'
    | '/login/'
    | '/admin/agent-envs'
    | '/admin/llm-providers'
    | '/admin/marketplaces'
    | '/admin/users'
    | '/agent/$agentId'
    | '/agent/creating'
    | '/agentic-teams/$teamId'
    | '/catalog/agents'
    | '/credential/$credentialId'
    | '/dashboards/$dashboardId'
    | '/knowledge-source/$sourceId'
    | '/session/$sessionId'
    | '/task/$taskId'
    | '/tasks/$shortCode'
    | '/credentials/oauth/callback'
    | '/mcp-providers/oauth/callback'
    | '/agentic-teams'
    | '/catalog/'
    | '/dashboards'
    | '/sessions/'
    | '/tasks'
    | '/admin/marketplace/$marketplaceId'
    | '/agent/$agentId/conversations'
    | '/catalog/agents/install'
    | '/environment/$envId/database'
    | '/environment/$envId/file'
    | '/sessions/agent/$agentId'
    | '/admin/marketplace/plugin/$pluginId'
    | '/catalog/agents/install/$bundleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/activities'
    | '/activities-all'
    | '/agents'
    | '/credentials'
    | '/knowledge-sources'
    | '/settings'
    | '/agent-api-spec/$agentId'
    | '/app-auth/consent'
    | '/dashboard-fullscreen/$dashboardId'
    | '/desktop-auth/consent'
    | '/guest/$guestShareToken'
    | '/guest/file-viewer'
    | '/login/mfa'
    | '/oauth/mcp-consent'
    | '/webapp/$webappToken'
    | '/'
    | '/login'
    | '/admin/agent-envs'
    | '/admin/llm-providers'
    | '/admin/marketplaces'
    | '/admin/users'
    | '/agent/$agentId'
    | '/agent/creating'
    | '/agentic-teams/$teamId'
    | '/catalog/agents'
    | '/credential/$credentialId'
    | '/dashboards/$dashboardId'
    | '/knowledge-source/$sourceId'
    | '/session/$sessionId'
    | '/task/$taskId'
    | '/tasks/$shortCode'
    | '/credentials/oauth/callback'
    | '/mcp-providers/oauth/callback'
    | '/agentic-teams'
    | '/catalog'
    | '/dashboards'
    | '/sessions'
    | '/tasks'
    | '/admin/marketplace/$marketplaceId'
    | '/agent/$agentId/conversations'
    | '/catalog/agents/install'
    | '/environment/$envId/database'
    | '/environment/$envId/file'
    | '/sessions/agent/$agentId'
    | '/admin/marketplace/plugin/$pluginId'
    | '/catalog/agents/install/$bundleId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/activities'
    | '/_layout/activities-all'
    | '/_layout/agents'
    | '/_layout/catalog'
    | '/_layout/credentials'
    | '/_layout/knowledge-sources'
    | '/_layout/sessions'
    | '/_layout/settings'
    | '/agent-api-spec/$agentId'
    | '/app-auth/consent'
    | '/dashboard-fullscreen/$dashboardId'
    | '/desktop-auth/consent'
    | '/guest/$guestShareToken'
    | '/guest/file-viewer'
    | '/login/mfa'
    | '/oauth/mcp-consent'
    | '/webapp/$webappToken'
    | '/_layout/'
    | '/login/'
    | '/_layout/admin/agent-envs'
    | '/_layout/admin/llm-providers'
    | '/_layout/admin/marketplaces'
    | '/_layout/admin/users'
    | '/_layout/agent/$agentId'
    | '/_layout/agent/creating'
    | '/_layout/agentic-teams/$teamId'
    | '/_layout/catalog/agents'
    | '/_layout/credential/$credentialId'
    | '/_layout/dashboards/$dashboardId'
    | '/_layout/knowledge-source/$sourceId'
    | '/_layout/session/$sessionId'
    | '/_layout/task/$taskId'
    | '/_layout/tasks/$shortCode'
    | '/credentials/oauth/callback'
    | '/mcp-providers/oauth/callback'
    | '/_layout/agentic-teams/'
    | '/_layout/catalog/'
    | '/_layout/dashboards/'
    | '/_layout/sessions/'
    | '/_layout/tasks/'
    | '/_layout/admin/marketplace/$marketplaceId'
    | '/_layout/agent/$agentId/conversations'
    | '/_layout/catalog/agents/install'
    | '/_layout/environment/$envId/database'
    | '/_layout/environment/$envId/file'
    | '/_layout/sessions/agent/$agentId'
    | '/_layout/admin/marketplace/plugin/$pluginId'
    | '/_layout/catalog/agents/install/$bundleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AgentApiSpecAgentIdRoute: typeof AgentApiSpecAgentIdRoute
  AppAuthConsentRoute: typeof AppAuthConsentRoute
  DashboardFullscreenDashboardIdRoute: typeof DashboardFullscreenDashboardIdRoute
  DesktopAuthConsentRoute: typeof DesktopAuthConsentRoute
  GuestGuestShareTokenRoute: typeof GuestGuestShareTokenRoute
  GuestFileViewerRoute: typeof GuestFileViewerRoute
  OauthMcpConsentRoute: typeof OauthMcpConsentRoute
  WebappWebappTokenRoute: typeof WebappWebappTokenRoute
  CredentialsOauthCallbackRoute: typeof CredentialsOauthCallbackRoute
  McpProvidersOauthCallbackRoute: typeof McpProvidersOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/webapp/$webappToken': {
      id: '/webapp/$webappToken'
      path: '/webapp/$webappToken'
      fullPath: '/webapp/$webappToken'
      preLoaderRoute: typeof WebappWebappTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/mcp-consent': {
      id: '/oauth/mcp-consent'
      path: '/oauth/mcp-consent'
      fullPath: '/oauth/mcp-consent'
      preLoaderRoute: typeof OauthMcpConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/mfa': {
      id: '/login/mfa'
      path: '/mfa'
      fullPath: '/login/mfa'
      preLoaderRoute: typeof LoginMfaRouteImport
      parentRoute: typeof LoginRoute
    }
    '/guest/file-viewer': {
      id: '/guest/file-viewer'
      path: '/guest/file-viewer'
      fullPath: '/guest/file-viewer'
      preLoaderRoute: typeof GuestFileViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest/$guestShareToken': {
      id: '/guest/$guestShareToken'
      path: '/guest/$guestShareToken'
      fullPath: '/guest/$guestShareToken'
      preLoaderRoute: typeof GuestGuestShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop-auth/consent': {
      id: '/desktop-auth/consent'
      path: '/desktop-auth/consent'
      fullPath: '/desktop-auth/consent'
      preLoaderRoute: typeof DesktopAuthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-fullscreen/$dashboardId': {
      id: '/dashboard-fullscreen/$dashboardId'
      path: '/dashboard-fullscreen/$dashboardId'
      fullPath: '/dashboard-fullscreen/$dashboardId'
      preLoaderRoute: typeof DashboardFullscreenDashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-auth/consent': {
      id: '/app-auth/consent'
      path: '/app-auth/consent'
      fullPath: '/app-auth/consent'
      preLoaderRoute: typeof AppAuthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-api-spec/$agentId': {
      id: '/agent-api-spec/$agentId'
      path: '/agent-api-spec/$agentId'
      fullPath: '/agent-api-spec/$agentId'
      preLoaderRoute: typeof AgentApiSpecAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sessions': {
      id: '/_layout/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof LayoutSessionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/knowledge-sources': {
      id: '/_layout/knowledge-sources'
      path: '/knowledge-sources'
      fullPath: '/knowledge-sources'
      preLoaderRoute: typeof LayoutKnowledgeSourcesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/credentials': {
      id: '/_layout/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof LayoutCredentialsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/catalog': {
      id: '/_layout/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof LayoutCatalogRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agents': {
      id: '/_layout/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof LayoutAgentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/activities-all': {
      id: '/_layout/activities-all'
      path: '/activities-all'
      fullPath: '/activities-all'
      preLoaderRoute: typeof LayoutActivitiesAllRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/activities': {
      id: '/_layout/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof LayoutActivitiesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tasks/': {
      id: '/_layout/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof LayoutTasksIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sessions/': {
      id: '/_layout/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof LayoutSessionsIndexRouteImport
      parentRoute: typeof LayoutSessionsRoute
    }
    '/_layout/dashboards/': {
      id: '/_layout/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof LayoutDashboardsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/catalog/': {
      id: '/_layout/catalog/'
      path: '/'
      fullPath: '/catalog/'
      preLoaderRoute: typeof LayoutCatalogIndexRouteImport
      parentRoute: typeof LayoutCatalogRoute
    }
    '/_layout/agentic-teams/': {
      id: '/_layout/agentic-teams/'
      path: '/agentic-teams'
      fullPath: '/agentic-teams'
      preLoaderRoute: typeof LayoutAgenticTeamsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/mcp-providers/oauth/callback': {
      id: '/mcp-providers/oauth/callback'
      path: '/mcp-providers/oauth/callback'
      fullPath: '/mcp-providers/oauth/callback'
      preLoaderRoute: typeof McpProvidersOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials/oauth/callback': {
      id: '/credentials/oauth/callback'
      path: '/credentials/oauth/callback'
      fullPath: '/credentials/oauth/callback'
      preLoaderRoute: typeof CredentialsOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/tasks/$shortCode': {
      id: '/_layout/tasks/$shortCode'
      path: '/tasks/$shortCode'
      fullPath: '/tasks/$shortCode'
      preLoaderRoute: typeof LayoutTasksShortCodeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/task/$taskId': {
      id: '/_layout/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/task/$taskId'
      preLoaderRoute: typeof LayoutTaskTaskIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/session/$sessionId': {
      id: '/_layout/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof LayoutSessionSessionIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/knowledge-source/$sourceId': {
      id: '/_layout/knowledge-source/$sourceId'
      path: '/knowledge-source/$sourceId'
      fullPath: '/knowledge-source/$sourceId'
      preLoaderRoute: typeof LayoutKnowledgeSourceSourceIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboards/$dashboardId': {
      id: '/_layout/dashboards/$dashboardId'
      path: '/dashboards/$dashboardId'
      fullPath: '/dashboards/$dashboardId'
      preLoaderRoute: typeof LayoutDashboardsDashboardIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/credential/$credentialId': {
      id: '/_layout/credential/$credentialId'
      path: '/credential/$credentialId'
      fullPath: '/credential/$credentialId'
      preLoaderRoute: typeof LayoutCredentialCredentialIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/catalog/agents': {
      id: '/_layout/catalog/agents'
      path: '/agents'
      fullPath: '/catalog/agents'
      preLoaderRoute: typeof LayoutCatalogAgentsRouteImport
      parentRoute: typeof LayoutCatalogRoute
    }
    '/_layout/agentic-teams/$teamId': {
      id: '/_layout/agentic-teams/$teamId'
      path: '/agentic-teams/$teamId'
      fullPath: '/agentic-teams/$teamId'
      preLoaderRoute: typeof LayoutAgenticTeamsTeamIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agent/creating': {
      id: '/_layout/agent/creating'
      path: '/agent/creating'
      fullPath: '/agent/creating'
      preLoaderRoute: typeof LayoutAgentCreatingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agent/$agentId': {
      id: '/_layout/agent/$agentId'
      path: '/agent/$agentId'
      fullPath: '/agent/$agentId'
      preLoaderRoute: typeof LayoutAgentAgentIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/users': {
      id: '/_layout/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof LayoutAdminUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/marketplaces': {
      id: '/_layout/admin/marketplaces'
      path: '/admin/marketplaces'
      fullPath: '/admin/marketplaces'
      preLoaderRoute: typeof LayoutAdminMarketplacesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/llm-providers': {
      id: '/_layout/admin/llm-providers'
      path: '/admin/llm-providers'
      fullPath: '/admin/llm-providers'
      preLoaderRoute: typeof LayoutAdminLlmProvidersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/agent-envs': {
      id: '/_layout/admin/agent-envs'
      path: '/admin/agent-envs'
      fullPath: '/admin/agent-envs'
      preLoaderRoute: typeof LayoutAdminAgentEnvsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sessions/agent/$agentId': {
      id: '/_layout/sessions/agent/$agentId'
      path: '/agent/$agentId'
      fullPath: '/sessions/agent/$agentId'
      preLoaderRoute: typeof LayoutSessionsAgentAgentIdRouteImport
      parentRoute: typeof LayoutSessionsRoute
    }
    '/_layout/environment/$envId/file': {
      id: '/_layout/environment/$envId/file'
      path: '/environment/$envId/file'
      fullPath: '/environment/$envId/file'
      preLoaderRoute: typeof LayoutEnvironmentEnvIdFileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/environment/$envId/database': {
      id: '/_layout/environment/$envId/database'
      path: '/environment/$envId/database'
      fullPath: '/environment/$envId/database'
      preLoaderRoute: typeof LayoutEnvironmentEnvIdDatabaseRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/catalog/agents/install': {
      id: '/_layout/catalog/agents/install'
      path: '/install'
      fullPath: '/catalog/agents/install'
      preLoaderRoute: typeof LayoutCatalogAgentsInstallRouteImport
      parentRoute: typeof LayoutCatalogAgentsRoute
    }
    '/_layout/agent/$agentId/conversations': {
      id: '/_layout/agent/$agentId/conversations'
      path: '/conversations'
      fullPath: '/agent/$agentId/conversations'
      preLoaderRoute: typeof LayoutAgentAgentIdConversationsRouteImport
      parentRoute: typeof LayoutAgentAgentIdRoute
    }
    '/_layout/admin/marketplace/$marketplaceId': {
      id: '/_layout/admin/marketplace/$marketplaceId'
      path: '/admin/marketplace/$marketplaceId'
      fullPath: '/admin/marketplace/$marketplaceId'
      preLoaderRoute: typeof LayoutAdminMarketplaceMarketplaceIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/catalog/agents/install/$bundleId': {
      id: '/_layout/catalog/agents/install/$bundleId'
      path: '/$bundleId'
      fullPath: '/catalog/agents/install/$bundleId'
      preLoaderRoute: typeof LayoutCatalogAgentsInstallBundleIdRouteImport
      parentRoute: typeof LayoutCatalogAgentsInstallRoute
    }
    '/_layout/admin/marketplace/plugin/$pluginId': {
      id: '/_layout/admin/marketplace/plugin/$pluginId'
      path: '/admin/marketplace/plugin/$pluginId'
      fullPath: '/admin/marketplace/plugin/$pluginId'
      preLoaderRoute: typeof LayoutAdminMarketplacePluginPluginIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutCatalogAgentsInstallRouteChildren {
  LayoutCatalogAgentsInstallBundleIdRoute: typeof LayoutCatalogAgentsInstallBundleIdRoute
}

const LayoutCatalogAgentsInstallRouteChildren: LayoutCatalogAgentsInstallRouteChildren =
  {
    LayoutCatalogAgentsInstallBundleIdRoute:
      LayoutCatalogAgentsInstallBundleIdRoute,
  }

const LayoutCatalogAgentsInstallRouteWithChildren =
  LayoutCatalogAgentsInstallRoute._addFileChildren(
    LayoutCatalogAgentsInstallRouteChildren,
  )

interface LayoutCatalogAgentsRouteChildren {
  LayoutCatalogAgentsInstallRoute: typeof LayoutCatalogAgentsInstallRouteWithChildren
}

const LayoutCatalogAgentsRouteChildren: LayoutCatalogAgentsRouteChildren = {
  LayoutCatalogAgentsInstallRoute: LayoutCatalogAgentsInstallRouteWithChildren,
}

const LayoutCatalogAgentsRouteWithChildren =
  LayoutCatalogAgentsRoute._addFileChildren(LayoutCatalogAgentsRouteChildren)

interface LayoutCatalogRouteChildren {
  LayoutCatalogAgentsRoute: typeof LayoutCatalogAgentsRouteWithChildren
  LayoutCatalogIndexRoute: typeof LayoutCatalogIndexRoute
}

const LayoutCatalogRouteChildren: LayoutCatalogRouteChildren = {
  LayoutCatalogAgentsRoute: LayoutCatalogAgentsRouteWithChildren,
  LayoutCatalogIndexRoute: LayoutCatalogIndexRoute,
}

const LayoutCatalogRouteWithChildren = LayoutCatalogRoute._addFileChildren(
  LayoutCatalogRouteChildren,
)

interface LayoutSessionsRouteChildren {
  LayoutSessionsIndexRoute: typeof LayoutSessionsIndexRoute
  LayoutSessionsAgentAgentIdRoute: typeof LayoutSessionsAgentAgentIdRoute
}

const LayoutSessionsRouteChildren: LayoutSessionsRouteChildren = {
  LayoutSessionsIndexRoute: LayoutSessionsIndexRoute,
  LayoutSessionsAgentAgentIdRoute: LayoutSessionsAgentAgentIdRoute,
}

const LayoutSessionsRouteWithChildren = LayoutSessionsRoute._addFileChildren(
  LayoutSessionsRouteChildren,
)

interface LayoutAgentAgentIdRouteChildren {
  LayoutAgentAgentIdConversationsRoute: typeof LayoutAgentAgentIdConversationsRoute
}

const LayoutAgentAgentIdRouteChildren: LayoutAgentAgentIdRouteChildren = {
  LayoutAgentAgentIdConversationsRoute: LayoutAgentAgentIdConversationsRoute,
}

const LayoutAgentAgentIdRouteWithChildren =
  LayoutAgentAgentIdRoute._addFileChildren(LayoutAgentAgentIdRouteChildren)

interface LayoutRouteChildren {
  LayoutActivitiesRoute: typeof LayoutActivitiesRoute
  LayoutActivitiesAllRoute: typeof LayoutActivitiesAllRoute
  LayoutAgentsRoute: typeof LayoutAgentsRoute
  LayoutCatalogRoute: typeof LayoutCatalogRouteWithChildren
  LayoutCredentialsRoute: typeof LayoutCredentialsRoute
  LayoutKnowledgeSourcesRoute: typeof LayoutKnowledgeSourcesRoute
  LayoutSessionsRoute: typeof LayoutSessionsRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAdminAgentEnvsRoute: typeof LayoutAdminAgentEnvsRoute
  LayoutAdminLlmProvidersRoute: typeof LayoutAdminLlmProvidersRoute
  LayoutAdminMarketplacesRoute: typeof LayoutAdminMarketplacesRoute
  LayoutAdminUsersRoute: typeof LayoutAdminUsersRoute
  LayoutAgentAgentIdRoute: typeof LayoutAgentAgentIdRouteWithChildren
  LayoutAgentCreatingRoute: typeof LayoutAgentCreatingRoute
  LayoutAgenticTeamsTeamIdRoute: typeof LayoutAgenticTeamsTeamIdRoute
  LayoutCredentialCredentialIdRoute: typeof LayoutCredentialCredentialIdRoute
  LayoutDashboardsDashboardIdRoute: typeof LayoutDashboardsDashboardIdRoute
  LayoutKnowledgeSourceSourceIdRoute: typeof LayoutKnowledgeSourceSourceIdRoute
  LayoutSessionSessionIdRoute: typeof LayoutSessionSessionIdRoute
  LayoutTaskTaskIdRoute: typeof LayoutTaskTaskIdRoute
  LayoutTasksShortCodeRoute: typeof LayoutTasksShortCodeRoute
  LayoutAgenticTeamsIndexRoute: typeof LayoutAgenticTeamsIndexRoute
  LayoutDashboardsIndexRoute: typeof LayoutDashboardsIndexRoute
  LayoutTasksIndexRoute: typeof LayoutTasksIndexRoute
  LayoutAdminMarketplaceMarketplaceIdRoute: typeof LayoutAdminMarketplaceMarketplaceIdRoute
  LayoutEnvironmentEnvIdDatabaseRoute: typeof LayoutEnvironmentEnvIdDatabaseRoute
  LayoutEnvironmentEnvIdFileRoute: typeof LayoutEnvironmentEnvIdFileRoute
  LayoutAdminMarketplacePluginPluginIdRoute: typeof LayoutAdminMarketplacePluginPluginIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutActivitiesRoute: LayoutActivitiesRoute,
  LayoutActivitiesAllRoute: LayoutActivitiesAllRoute,
  LayoutAgentsRoute: LayoutAgentsRoute,
  LayoutCatalogRoute: LayoutCatalogRouteWithChildren,
  LayoutCredentialsRoute: LayoutCredentialsRoute,
  LayoutKnowledgeSourcesRoute: LayoutKnowledgeSourcesRoute,
  LayoutSessionsRoute: LayoutSessionsRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAdminAgentEnvsRoute: LayoutAdminAgentEnvsRoute,
  LayoutAdminLlmProvidersRoute: LayoutAdminLlmProvidersRoute,
  LayoutAdminMarketplacesRoute: LayoutAdminMarketplacesRoute,
  LayoutAdminUsersRoute: LayoutAdminUsersRoute,
  LayoutAgentAgentIdRoute: LayoutAgentAgentIdRouteWithChildren,
  LayoutAgentCreatingRoute: LayoutAgentCreatingRoute,
  LayoutAgenticTeamsTeamIdRoute: LayoutAgenticTeamsTeamIdRoute,
  LayoutCredentialCredentialIdRoute: LayoutCredentialCredentialIdRoute,
  LayoutDashboardsDashboardIdRoute: LayoutDashboardsDashboardIdRoute,
  LayoutKnowledgeSourceSourceIdRoute: LayoutKnowledgeSourceSourceIdRoute,
  LayoutSessionSessionIdRoute: LayoutSessionSessionIdRoute,
  LayoutTaskTaskIdRoute: LayoutTaskTaskIdRoute,
  LayoutTasksShortCodeRoute: LayoutTasksShortCodeRoute,
  LayoutAgenticTeamsIndexRoute: LayoutAgenticTeamsIndexRoute,
  LayoutDashboardsIndexRoute: LayoutDashboardsIndexRoute,
  LayoutTasksIndexRoute: LayoutTasksIndexRoute,
  LayoutAdminMarketplaceMarketplaceIdRoute:
    LayoutAdminMarketplaceMarketplaceIdRoute,
  LayoutEnvironmentEnvIdDatabaseRoute: LayoutEnvironmentEnvIdDatabaseRoute,
  LayoutEnvironmentEnvIdFileRoute: LayoutEnvironmentEnvIdFileRoute,
  LayoutAdminMarketplacePluginPluginIdRoute:
    LayoutAdminMarketplacePluginPluginIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface LoginRouteChildren {
  LoginMfaRoute: typeof LoginMfaRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginMfaRoute: LoginMfaRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AgentApiSpecAgentIdRoute: AgentApiSpecAgentIdRoute,
  AppAuthConsentRoute: AppAuthConsentRoute,
  DashboardFullscreenDashboardIdRoute: DashboardFullscreenDashboardIdRoute,
  DesktopAuthConsentRoute: DesktopAuthConsentRoute,
  GuestGuestShareTokenRoute: GuestGuestShareTokenRoute,
  GuestFileViewerRoute: GuestFileViewerRoute,
  OauthMcpConsentRoute: OauthMcpConsentRoute,
  WebappWebappTokenRoute: WebappWebappTokenRoute,
  CredentialsOauthCallbackRoute: CredentialsOauthCallbackRoute,
  McpProvidersOauthCallbackRoute: McpProvidersOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
